### PR TITLE
Backport healthcheck changes to branch 1.4.3 and fix failing tests

### PR DESCRIPTION
**Pull request by bsimonova**
Description:
Backport changes for healthcheck issues to branch 1.4.3 for healthcheck files only,
fix print list_checks to log in lib389 and minor change to tests for dsidm and healthcheck
to prevent failing.

Relates: https://github.com/389ds/389-ds-base/issues/3926
Relates: https://github.com/389ds/389-ds-base/issues/3894
Relates: https://github.com/389ds/389-ds-base/issues/3894
Relates: https://github.com/389ds/389-ds-base/issues/3801
Relates: https://github.com/389ds/389-ds-base/issues/4144
Relates: https://github.com/389ds/389-ds-base/issues/4159

### CODE REVIEW

**Comment by mreynolds389** [comment]
LGTM

**Comment by Firstyear** [comment]
@mreynolds389 I think you may need to merge this, I don't think @bsimonova has commit rights ?

**Comment by mreynolds389** [comment]
> @mreynolds389 I think you may need to merge this, I don't think @bsimonova has commit rights ?

The commit message needs to be updated to reflect the reviewer.  I think there is a way to get github to automatically add the reviewer.  Freeipa's PR's work that way - need to look into that...

**Comment by Firstyear** [comment]
I think if you use squash and merge you can change the commit message via github, but it may affect the authorship of the commit.

**Review by droideck — APPROVED** [review]
LGTM too!
I can merge if you want (it doesn't affect the authorship of the commit).

**Comment by bsimonova** [comment]
Thanks guys for review, I got my rights back, so I can merge it when I change the commit message :)

**Pull request merged**
