### PR TITLE
Issue 6375 - UI - Update cockpit.js code to the latest version

### LINKED ISSUE #6375: UI - Update cockpit.js code to the latest version
We need to update `src/cockpit/389-console/pkg/lib/cockpit.js` to the latest version. The recent updates shown at [this link](https://github.com/cockpit-project/cockpit/blob/c9ddba2b5719f1ca7bfa7b09853d5fece846f1c0/pkg/lib/cockpit/_internal/common.ts#L68) indicate improvements. Therefore, we should upgrade at least `cockpit.js`, and possibly update the entire `src/cockpit/389-console/pkg/lib` directory from [Cockpit's repository](https://github.com/cockpit-project/cockpit/tree/main/pkg/lib).

It has Patternly 5 in package.json so we might need to do the full upgrade - https://github.com/389ds/389-ds-base/issues/6024

### PR DESCRIPTION
**Pull request by droideck**
Description: Update src/cockpit/389-console/pkg/lib/cockpit.js to the latest version.
Update the entire src/cockpit/389-console/pkg/lib directory from Cockpit's repository.
Update package.json.

Fixes: https://github.com/389ds/389-ds-base/issues/6375

Reviewed by: ?

### CODE REVIEW

**Comment by droideck** [comment]
Okay, I've tried to do this without the Patternfly 4 -> 5 upgrade, and it didn't work correctly.
The porting should not be very hard, but it's a bit time-consuming. Select and table components are the main issues:
https://www.patternfly.org/get-started/upgrade/

I'll be back from PTO in 10 days. If we need it sooner, feel free to continue the PR. Otherwise, I'll finish when I return.

**Review by progier389 — APPROVED** [review]
Although I have not found anything suspicious, 
 because of the amount of changes, it is quite hard to understand the global impact.
 So my feeling is that we should go ahead and merge this PR then fully test cockpit again.

**Comment by droideck** [comment]
Okay, it's ready for review!
P.S. I still need to replace `FontAwesomeIcon`s as they throw warnings but it should not affect other content review.

**Comment by mreynolds389** [comment]
Not sure how you want to handle this, but your new tables seem to be missing the "compact" setting

```
--- a/src/cockpit/389-console/src/lib/server/errorLog.jsx
+++ b/src/cockpit/389-console/src/lib/server/errorLog.jsx
@@ -501,7 +501,7 @@ export class ServerErrorLog extends React.Component {
     handleOnSelect = (_event, isSelected, rowIndex) => {
         let disableSaveBtn = true;
         const rows = [...this.state.rows];
-        
+
         // Update the selected row
         rows[rowIndex].selected = isSelected;
 
@@ -596,6 +596,7 @@ export class ServerErrorLog extends React.Component {
                             <Table
                                 aria-label="Selectable Error Log Levels"
                                 className="ds-left-margin"
+                                variant="compact"
                             >
                                 <Thead>
                                     <Tr>
```

Not every table "is compact" but I think almost all of them were:

    variant={TableVariant.compact}   --->   variant="compact"

It might be easier to fix this now than in a different PR.  Thoughts?

**Comment by mreynolds389** [comment]
Browser crash 

Monitor -> Database -> "dc=example,dc=com":

```
suffixMonitor.jsx:166 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Function.<anonymous> (suffixMonitor.jsx:166:50)
    at process_queue (deferred.js:124:33)
    at deferred.js:137:31
    at later_drain (deferred.js:18:9)
```

Also, it looks like most of the tables are compact, so maybe it's just the logging level tables?

**Comment by mreynolds389** [comment]
> Browser crash
> 
> Monitor -> Database -> "dc=example,dc=com":
> 
> ```
> suffixMonitor.jsx:166 Uncaught TypeError: Cannot read properties of undefined (reading '0')
>     at Function.<anonymous> (suffixMonitor.jsx:166:50)
>     at process_queue (deferred.js:124:33)
>     at deferred.js:137:31
>     at later_drain (deferred.js:18:9)
> ```
> 

Ok this was not a regression in your patch.  This is also crashing in main (bdb vs mdb issue)

**Review by mreynolds389 — CHANGES_REQUESTED** [review]
Please update the logging level tables to be compact, and double check there are no more tables that might be missing the compact variant.  Otherwise looks good!!

**Review by mreynolds389 — APPROVED** [review]

**Pull request merged**
