### PR TITLE
Issue 4243 - Fix CI: SyncRepl plugin provides a wrong cookie

### PR DESCRIPTION
**Pull request by tbordaz**
Bug description:
	Individual testcase run fine but they fails when
	run in a raw

Fix description:
	Each testcase needs to do cleanup (at the end) or
        make initialization more robust

relates: https://github.com/389ds/389-ds-base/issues/4243

Reviewed by:

Platforms tested:  F31

### CODE REVIEW

**Comment by Firstyear** [comment]
@droideck thoughts? I'm wondering how to structure this as a fixture but I think I'm not seeing it?

**Comment by droideck** [comment]
I think this part can be a fixture:
https://github.com/389ds/389-ds-base/blob/db95b40b77790d7813b1edc03172399b31fb9664/dirsrvtests/tests/suites/syncrepl_plugin/basic_test.py#L271-L323

If I understand correctly.
But only for the last three tests:

- test_sync_repl_cookie
- test_sync_repl_cookie_add_del
- test_sync_repl_cookie_with_failure

**Comment by tbordaz** [comment]
Thanks @droideck for your comments. If this part of code becomes a fixture, the cleanup as no longer access to group or am_config. How should it (cleanup) proceed ? Deleting all group/am_config returned by a search ?

**Comment by droideck** [comment]
> Thanks @droideck for your comments. If this part of code becomes a fixture, the cleanup as no longer access to group or am_config. How should it (cleanup) proceed ? Deleting all group/am_config returned by a search ?

It's okay, you can add another finalizer to the fixture and it will be executed after the test case:

```
    def fin():
        for am_config in am_configs_cleanup:
            am_config.delete()
        for g in group:
            try:
                g.delete()
            except:
                pass

    request.addfinalizer(fin)
```

And the test case will have the finalizer for user only:

```
    def fin():
        inst.restart()
        for user in users_set:
            try:
                user.delete()
            except:
                pass

    request.addfinalizer(fin)
```

**Comment by tbordaz** [comment]
Thanks @droideck for your help and advices. I moved initialization of the 3 testcases (test_sync_repl_cookie,test_sync_repl_cookie_add_del and  test_sync_repl_cookie_with_failure) into a fixture.

**Review by droideck — APPROVED** [review]
Looks good to me! Thank you!

**Pull request merged**
