### PR TITLE
Issue 4169 - UI - migrate replication tables to PF4

### PR DESCRIPTION
**Pull request by mreynolds389**
Description:  

Migrated replication tables to PF 4 and cleaned up replication monitoring.

relates: https://github.com/389ds/389-ds-base/issues/4169

### CODE REVIEW

**Review by jchapma — COMMENTED** [review]
Looks good to me

**Review by droideck — APPROVED** [review]
Looks great! Ack

P.S. yeah, we really should thing about replacing Repl Monitor tabs report... I'll try to think more about this UI/UX solution...

**Comment by mreynolds389** [comment]
> Looks great! Ack
> 
> P.S. yeah, we really should thing about replacing Repl Monitor tabs report... I'll try to think more about this UI/UX solution...

Yeah, it's not terrible but could be better.  

In fact, if you noticed I took the repl and winsync agreements out of the monitor completely.   You can't get the status or lag time without the credentials so it's not really useful, so it's gone -> meaning we only have the "Sync Report" left.

**Comment by droideck** [comment]
> > Looks great! Ack
> > P.S. yeah, we really should thing about replacing Repl Monitor tabs report... I'll try to think more about this UI/UX solution...
> 
> Yeah, it's not terrible but could be better.
> 
> In fact, if you noticed I took the repl and winsync agreements out of the monitor completely. You can't get the status or lag time without the credentials so it's not really useful, so it's gone -> meaning we only have the "Sync Report" left.

Sounds good to me:) No objections on my side.

**Pull request merged**
