### PR TITLE
Issue 5954 - Disable Transparent Huge Pages v2

### LINKED ISSUE #5954: Disable Transparent Huge Pages
**Description of problem:**
As described in [bug 2068120](https://bugzilla.redhat.com/show_bug.cgi?id=2068120), THP can have negative effects on RHDS performance.
This seems to happen with large caches.
Some customers are getting uncontrolled memory usage while others are seeing high CPU consumption.
It would make sense to either disable THP for RHDS or at least add some messages in the errors logs.
RHDS healthcheck tool should also report when THP is enabled on the system.

**Version-Release number of selected component (if applicable):**
This is impacting all RHDS 11 and 12 versions.

**How reproducible:**
At customer sites.

**Steps to Reproduce:**
1. Configure large caches ( > 50 GB )
2. Check memory and CPU usage when RHDS is under heavy load
3. Disable THP ==> RHDS uses less memory and CPU

**Actual results:**
High memory and CPU usage.

**Expected results:**
Controlled memory and CPU usage.

**Additional info:**
    https://access.redhat.com/solutions/3799821

### PR DESCRIPTION
**Pull request by vashirov**
Bug Description:
THP can have negative effects on DS performance when large caches are
used.

Fix Description:
* Add a new variable for `ns-slapd` THP_DISABLE.
  When THP_DISABLE is set to 1, THP is disabled for `ns-slapd` process
  via `prctl(2)`. With any other value, THP settings are untouched.

Before:
```
$ grep THP /proc/$(pidof ns-slapd)/status
THP_enabled:    1
```

After
```
$ grep THP /proc/$(pidof ns-slapd)/status
THP_enabled:    0
```

* Add a new healthcheck linter, that checks if THP is disabled system-wide
  or per instance. In case THP is enabled for both the system and the
  process, it prints recommendations how to disable THP.

Fixes: https://github.com/389ds/389-ds-base/issues/5954

Reviewed-by: ???

### CODE REVIEW

**Review by tbordaz — APPROVED** [review]
Thanks LGTM
Let's see which option is preferred

**Comment by Firstyear** [comment]
My concern here is we are addressing the symptom not the problem. I think if we disable THP then we'll likely never turn it back on again, and we could be losing out on benefits. Shouldn't we pursue a fix to the underlying issue?

**Comment by vashirov** [comment]
I understand your concern. I think that the underlying issue is that THP is not applicable to certain workloads, where data access patterns are not contiguous, with a lot of small allocations and deallocations.
Some examples:
https://www.pingcap.com/blog/transparent-huge-pages-why-we-disable-it-for-databases/
https://www.mongodb.com/docs/manual/tutorial/transparent-huge-pages/
https://redis.io/docs/management/optimization/latency/#latency-induced-by-transparent-huge-pages
https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-HUGE-PAGES
https://docs.oracle.com/en/database/oracle/oracle-database/19/ladbi/disabling-transparent-hugepages.html

Every optimization is a tradeoff and comes with a cost. THP can reduce page faults, but in our case it also causes memory fragmentation, CPU spikes (`khugepaged` has a non-zero overhead) and latency spikes. If we can't take advantage of this optimization due to our workload and usage patterns, I see no reason to keep it enabled.

**Comment by Firstyear** [comment]
> Every optimization is a tradeoff and comes with a cost. THP can reduce page faults, but in our case it also causes memory fragmentation, CPU spikes (`khugepaged` has a non-zero overhead) and latency spikes. If we can't take advantage of this optimization due to our workload and usage patterns, I see no reason to keep it enabled.

Okay, lets disable it then.

**Review by Firstyear — APPROVED** [review]

**Comment by vashirov** [comment]
@Firstyear, thanks!

@tbordaz, any thoughts on the healthcheck part? Do you think it's still needed?

**Comment by tbordaz** [comment]
> @Firstyear, thanks!
> 
> @tbordaz, any thoughts on the healthcheck part? Do you think it's still needed?

IIUC, with the patch the server requests to disable THP for itself. So the benefit of healthcheck would be to double check that the request was successful. I think it worthes doing that check if it is not too complex to implement.

**Review by droideck — APPROVED** [review]

**Comment by vashirov** [comment]
I've added healthcheck linter and tests for it, please review.
Thanks!

**Comment by vashirov** [comment]
I fixed the test, now it passes. @tbordaz, please let me know if you're happy with the healthcheck changes, thanks.

**Comment by tbordaz** [comment]
> I fixed the test, now it passes. @tbordaz, please let me know if you're happy with the healthcheck changes, thanks.

Yes that looks perfect to me

**Pull request merged**
