### PR TITLE
Issue 5780 - add setting to control repl linger timeout

### PR DESCRIPTION
**Pull request by mreynolds389**
Description: 

Add new config settings: nsds5ReplicaLingerTimeout that be set in either the replica config entry (affecting all agreements), or in each agreement

relates: https://github.com/389ds/389-ds-base/issues/5780

### CODE REVIEW

**Review by progier389 — APPROVED** [review]
LGTM

**Review by droideck — APPROVED** [review]
Looks good!

**Review by Firstyear — APPROVED** [review]

**Comment by mreynolds389** [comment]
Waiting for customer feedback to see if this helps their situation.  

If it does not help the customer then I'd prefer to *not* merge this and just close it out.

**Comment by tbordaz** [comment]
@mreynolds389 no feedback before closure, so we can not say if it helped or not.
I agree that it is not clear how this tuning could help. I am closing the PR/ticket

**Pull request closed without merging**
