### PR TITLE
Remove stale zlib-devel dependency declaration

### PR DESCRIPTION
**Pull request by Flowdalic**

### CODE REVIEW

**Comment by Firstyear** [comment]
@mreynolds389 I don't have any issues with this

**Comment by mreynolds389** [comment]
The change is fine, but we need an Issue created to link to this PR, and a proper commit message will be required:

https://www.port389.org/docs/389ds/contributing.html#getting-the-patch-ready

**Comment by Flowdalic** [comment]
Created issue and adjusted commit message.

**Comment by mreynolds389** [comment]
> Created issue and adjusted commit message.

The commit message isn't exactly right.  Although it is self explanatory in the title, there is no "bug" and "fix" description.  In this case It's ok though :-)  Once the "checks" are complete I'll merge it.  Thanks!!

**Review by progier389 — APPROVED** [review]
I think it is time to merge this one. 
Note: it is just a cleanup commit of the snmp section, because in the mean time a new dependency toward zlib-devel has been added because of the log compression feature:
# Log compression
Requires:         zlib-devel

**Pull request merged**
