### PR TITLE
Issue 4127 - With Accounts/Account module delete fuction is not working

### PR DESCRIPTION
**Pull request by aadhikar**
Desciption: Added a test to verify delete function is working with Accounts/Account

Relates: https://github.com/389ds/389-ds-base/issues/4127

Reviewed by: @droideck

### CODE REVIEW

**Review by droideck — APPROVED** [review]
LGTM!
One small issue though - could you please move the test to `/home/vagrant/389-ds-base/dirsrvtests/tests/suites/lib389/idm` ? IIRC, we plan to move all of the tests from `src/lib389` to `dirsrvtests` at some point.

**Comment by aadhikar** [comment]
Sure no problem Thanks!

**Comment by aadhikar** [comment]
@droideck If you approve the changes I will update the commit message :)

**Comment by aadhikar** [comment]
@droideck Hey I already updated it so if approve feel free to merge, Thanks! :)

**Pull request merged**
