### PR TITLE
Issue 4469 - Backend redesign phase 3a - ( merge into master branch)

### PR DESCRIPTION
**Pull request by progier389**
This is the pull request about the merge of i4469 branch (that include the backend redesign phase 3a) into master branch
Note: diff is complex but  review already took place in the PR towards the i4469 branch

Design documentation is in [https://www.port389.org/docs/389ds/design/backend-redesign-phase3.html](https://www.port389.org/docs/389ds/design/backend-redesign-phase3.html)

Related Issue: [4469](https://github.com/389ds/389-ds-base/issues/4469)

Related PR: [4587](https://github.com/389ds/389-ds-base/pull/4587) [4546](https://github.com/389ds/389-ds-base/pull/4546)  [4495](https://github.com/389ds/389-ds-base/pull/4495) 

Reviewers: @Firstyear @tbordaz @mreynolds389

### CODE REVIEW

**Comment by progier389** [comment]
Still need to rebase to current master

**Comment by Firstyear** [comment]
Ack from me, especially given how much review this is had, and the "fun" to rebase it. I'd say merge sooner than later :)

**Comment by Firstyear** [comment]
Sorry to do this mate, decided to do a check, and hit an error:

```
 $ cat ns-slapd-standalone1.asan.14003
=================================================================
==14003==ERROR: AddressSanitizer: SEGV on unknown address 0x1fed8ac8fe68 (pc 0x7fb4562fdf88 bp 0x7fb436e16c60 sp 0x7fb436e168c0 T21)
==14003==The signal is caused by a READ memory access.
    #0 0x7fb4562fdf88 in dblayer_value_concat /home/william/development/389ds/ds/ldap/servers/slapd/back-ldbm/dbimpl.c:263:24
    #1 0x7fb45633f343 in index_read_ext_allids /home/william/development/389ds/ds/ldap/servers/slapd/back-ldbm/index.c:1038:9
    #2 0x7fb45633dc12 in index_read_ext /home/william/development/389ds/ds/ldap/servers/slapd/back-ldbm/index.c:1101:12
    #3 0x7fb45633db8d in index_read /home/william/development/389ds/ds/ldap/servers/slapd/back-ldbm/index.c:881:12
    #4 0x7fb4563f067d in uniqueid2entry /home/william/development/389ds/ds/ldap/servers/slapd/back-ldbm/uniqueid2entry.c:48:20
    #5 0x7fb4563077ed in get_copy_of_entry /home/william/development/389ds/ds/ldap/servers/slapd/back-ldbm/dn2entry.c:227:17
    #6 0x7fb456350ffa in ldbm_back_add /home/william/development/389ds/ds/ldap/servers/slapd/back-ldbm/ldbm_add.c:291:40
    #7 0x7fb465453ae4 in op_shared_add /home/william/development/389ds/ds/ldap/servers/slapd/add.c:758:18
    #8 0x7fb46545028c in do_add /home/william/development/389ds/ds/ldap/servers/slapd/add.c:236:9
    #9 0x382cb6 in connection_dispatch_operation /home/william/development/389ds/ds/ldap/servers/slapd/connection.c:620:9
    #10 0x3781ae in connection_threadmain /home/william/development/389ds/ds/ldap/servers/slapd/connection.c:1770:9
    #11 0x7fb4612e717a  (/usr/lib64/libnspr4.so+0x2a17a)
    #12 0x7fb460e894f8 in start_thread (/lib64/libpthread.so.0+0x84f8)
    #13 0x7fb46339afbe in clone (/lib64/libc.so.6+0xfbfbe)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/william/development/389ds/ds/ldap/servers/slapd/back-ldbm/dbimpl.c:263:24 in dblayer_value_concat
Thread T21 created by T0 here:
    #0 0x31cd9a in pthread_create /home/abuild/rpmbuild/BUILD/llvm-11.0.1.src/build/../projects/compiler-rt/lib/asan/asan_interceptors.cpp:214:3
    #1 0x7fb4612e6e59  (/usr/lib64/libnspr4.so+0x29e59)

==14003==ABORTING
```

This is with clang11/llvm11 on SLE 15.2, with your branch, and running the basic test suite.

**Comment by progier389** [comment]
Hi @Firstyear, don't feel sorry -;) the earlier we found these issue, the better !
That said, I have not reproduced the problem in my environment (added an entry happly and asan only reports the usual  setup_internal_backends leaks - not very surprising otherwise the pytests would have failed ) And I do not understand your problem when looking at the code:
clearly setup_internal_backends should be hardened o handle the len == 0 case,
but in your report you are in the nsuniqueid case which should not be empty ...
So either the problem is elsewhere (environment not in sync with myfork i4469 branch or upstream i4469 branch ? ) or there is a weird issue somewhere ...

**Comment by progier389** [comment]
There was indeed a problem in the branches (myfork/i4469 was missing a commit - (I probably pushed it without the --force option 
 so it went into upstream/i4469). I re-synchronized the branches.  
That said although the missing commit was important (without it the pytest replication setup fails) , it does not explain the asan error that you got. 
The more I think about it, the more it is weird. 
In a add operation the uniqueid is either provided by the ldap request or generated. But in both case that is code that is not changed by this PR. So IMHO the only way to get in trouble is that there was a stack or heap corruption not detected by libasan 
Anyway in all case we will need to reproduce the issue before having a chance   of fixing it.
@Firstyear,  what kind of test were you doing when ns-slapd exited , is the problem reproducible ?

**Comment by progier389** [comment]
Added a commit to harden dblayer_value_concat code if a value is empty (0 length)

**Comment by Firstyear** [comment]
> This is with clang11/llvm11 on SLE 15.2, with your branch, and running the basic test suite.

I can reproduce it every time. It's a clean system so no other artifacts. I can re-test with your new changes later.

**Comment by progier389** [comment]
I start to suspect that clang may not handle varargs exactly the same way than gcc does (if integer are not pushed on stack
 as long that would explain why I have no problem with gcc build while clang build breaks in a function using varargs).

**Comment by Firstyear** [comment]
I always try to avoid va-args if I can, but this code probably has existed this way for a while. When you say 1L or 0L in the caller, what do you mean?

**Comment by progier389** [comment]
The old code was not using varargs.  0L or 1L to get a long rather than an int.
But anyway the issue is not there:

I build a clang env on my machine then I build 389 over clang and:
   I have done a few test about varags and:
     [1] my suspicion was wrong:  clang behaves as gcc and promotes int to long when calling functions
           (so there is no prblem if int and size_t get mixed in the varags list.)
     [2]  py.test run happily on suites/basic:  
============= 36 passed, 9 skipped, 154 warnings in 169.63 seconds =============

So I have no idea of what could be your problem ...
I just hope that the last set of commits fixed your problem
  if not we can try to replace the varargs by fixed size parameters (in practice we concat either two or 3 strings) 
  and if it still crash I  will need your help to debug the issue (first by adding traces that logs the 
    va_arg values, )

**Comment by Firstyear** [comment]
I tried with the latest commits and it still fails sorry :( :(

**Comment by progier389** [comment]
Last commit replaces the varargs by fixed size parameters in dblayer_value_concat.
@Firstyear could you test if it fix the issue (and investigate it if that is not the case ... )

**Comment by Firstyear** [comment]
Your latest fixes resolve the issue! Thank you @progier389!

**Comment by progier389** [comment]
That is a good news ! Thank you for the test @Firstyear 
The bad news was about the additional PR checks that were added a few days ago:
It shows that there is at least a range filter issue. (I fixed it, will check if these test are OK (except the 3 ones that fails on other PR (i.e aci, paged_search and plugins))

**Comment by Firstyear** [comment]
@progier389 As mentioned in the meeting, and @tbordaz agreed, I think we should merge this "as is", and we can resolve the smaller issues as we continue to reduce the rebase-merge pain. :)

**Comment by tbordaz** [comment]
On the review side, the patch looks good to me. On the test side as well (PR-CI, asan,..) the fix does not show regression. So you have my ACK
It remains a task to run freeipa acceptance with your patch.

**Comment by Firstyear** [comment]
> On the review side, the patch looks good to me. On the test side as well (PR-CI, asan,..) the fix does not show regression. So you have my ACK
> It remains a task to run freeipa acceptance with your patch.

I think we should merge this without the freeipa acceptance and we just fix anything we find after?

**Comment by progier389** [comment]
IPA Tests were OK. (https://github.com/freeipa-pr-ci2/freeipa/pull/707)
I just rebased from master (got only one conflict about a warning fix in filtercmp) 
And will merge once the PR Checks are OK.

**Comment by progier389** [comment]
OK, only the 3 usual failure ==> time for the big merge

**Comment by tbordaz** [comment]
Champagne (or cider) !!!

**Comment by vashirov** [comment]
@progier389, I see only one commit merged, shouldn't be there more?

**Pull request merged**
