### PR TITLE
Issue 5450 - schema - nsAccountLock should be single valued

### LINKED ISSUE #5450: nsAccountLock should be single valued
**Issue Description**

Currently nsAccountLockout is multivalued when it should be single valued

### PR DESCRIPTION
**Pull request by mreynolds389**
Description:  nsAccountLock should be single valued

fixes: https://github.com/389ds/389-ds-base/issues/5450

### CODE REVIEW

**Comment by tbordaz** [comment]
Did you test the PR in MMR S1-S2, S1 having this change and S2 having not this change ?
I have a doubt that 'single-valued' will be successfully push against 'multi-valued'

**Comment by mreynolds389** [comment]
Yes I need to test replication in both directions when the schema changes.  It's possible this might need to wait for schema replication improvements...

**Comment by mreynolds389** [comment]
> Yes I need to test replication in both directions when the schema changes. It's possible this might need to wait for schema replication improvements...

@tbordaz - Well schema replication is not working.  The consumer's schema is not updated, and I see no error messages on either replica's logs (with repl logging enabled).  So I don't think it's detecting that the schema is different in regards to single vs multivalued.  I'll investigate....

**Comment by mreynolds389** [comment]
> > Yes I need to test replication in both directions when the schema changes. It's possible this might need to wait for schema replication improvements...
> 
> @tbordaz - Well schema replication is not working. The consumer's schema is not updated, and I see no error messages on either replica's logs (with repl logging enabled). So I don't think it's detecting that the schema is different in regards to single vs multivalued. I'll investigate....

Ok if I live update the schema, then it does trigger schema replication (schema CSN was previously null after install).  Then I see the failure:

```
[16/Dec/2022:13:13:14.122512949 -0500] - DEBUG - schema_at_compare - local supplier schema attribute [nsAccountLock] is not "single-valued" 
[16/Dec/2022:13:13:14.137866487 -0500] - DEBUG - schema_at_superset_check - Remote nsAccountLock schema attributetypes is a superset of the received one.
[16/Dec/2022:13:13:14.145499551 -0500] - DEBUG - schema_at_superset_check - Fail to retrieve in the local supplier schema [nsslapd-conntablesize or 2.16.840.1.113730.3.1.2247]
[16/Dec/2022:13:13:14.169673186 -0500] - DEBUG - schema_at_compare - remote consumer schema attribute [nsAccountLock] is not "single-valued" 
[16/Dec/2022:13:13:14.175907362 -0500] - DEBUG - schema_list_attr2learn - Add that unknown/extended attribute nsAccountLock (2.16.840.1.113730.3.1.610)
[16/Dec/2022:13:13:14.183878665 -0500] - DEBUG - schema_list_attr2learn - Add that unknown/extended attribute nsslapd-conntablesize (2.16.840.1.113730.3.1.2247)
[16/Dec/2022:13:13:14.192949109 -0500] - DEBUG - schema - supplier takes attributetypes: ( 2.16.840.1.113730.3.1.2247 NAME 'nsslapd-conntablesize' DESC 'Netscape defined attribute type' SYNTAX 1.3.6.1.4.1.1466.115.121.1.27 SINGLE-VALUE X-ORIGIN 'Netscape Directory Server' )
[16/Dec/2022:13:13:14.199242004 -0500] - DEBUG - schema - supplier takes attributetypes: ( 2.16.840.1.113730.3.1.610 NAME 'nsAccountLock' DESC 'Operational attribute for Account Inactivation' SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 USAGE directoryOperation X-ORIGIN 'Netscape Directory Server' )
[16/Dec/2022:13:13:14.205489329 -0500] - DEBUG - modify_schema_prepare_mods - MOD[0] add (attributetypes): ( 2.16.840.1.113730.3.1.2247 NAME 'nsslapd-conntablesize' DESC 'Netscape defined attribute type' SYNTAX 1.3.6.1.4.1.1466.115.121.1.27 SINGLE-VALUE X-ORIGIN 'Netscape Directory Server' )
[16/Dec/2022:13:13:14.211718559 -0500] - DEBUG - modify_schema_prepare_mods - MOD[1] add (attributetypes): ( 2.16.840.1.113730.3.1.610 NAME 'nsAccountLock' DESC 'Operational attribute for Account Inactivation' SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 USAGE directoryOperation X-ORIGIN 'Netscape Directory Server' )
[16/Dec/2022:13:13:14.218283245 -0500] - DEBUG - modify_schema_internal_mod - Successfully learn attributetypes definitions
[16/Dec/2022:13:13:14.224581281 -0500] - ERR - NSMMReplicationPlugin - update_consumer_schema - [S] Schema agmt="cn=beakerBox" (kvm-06-guest12:389) must not be overwritten (set replication log for additional info)
[16/Dec/2022:13:13:14.230846800 -0500] - DEBUG - NSMMReplicationPlugin - conn_push_schema - [S] schema definitions may have been learned
[16/Dec/2022:13:13:14.827480889 -0500] - DEBUG - NSMMReplicationPlugin - conn_push_schema - Schema checking successful: ok to push the schema (agmt="cn=beakerBox" (kvm-06-guest12:389))
```

It's not entirely clear to me why it failed looking at the logs.  I guess it's this line:

```
[16/Dec/2022:13:13:14.137866487 -0500] - DEBUG - schema_at_superset_check - Remote nsAccountLock schema attributetypes is a superset of the received one.
```

But the other logging messages make it appear that schema replication did work.  So this should be improved somehow.

**Review by Firstyear — APPROVED** [review]
going to approve because this change is "correct", but also could we consider as a saftey to have checks on nsAccountLock check if it's multivalue and then if any value is true, consider locked?

**Pull request closed without merging**
