### PR TITLE
Issue 4361 - RFE - add - dscreate --advanced flag to avoid user confusion

### LINKED ISSUE #4361: dscreate template options can create some confusion
It has been noticed in a few seperate reports that certain options in the dscreate template can cause confusion. This is because when presented with the options, people may attempt to tweak or change settings to "customise" them, without fully understanding the impact.

Many settings in the template exist to assist developers with prefix builds, or are compatibilities from legacy setup-ds.pl. 

The options won't be removed, but we should have dscreate template only show "common" options, and a --advanced flag that displays *all* options to help guide admins in the general case to only having visible set of options that are relevant.

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: It has been noticed in a few seperate reports that
certain options in the dscreate template can cause confusion. This
is because when presented with the options, people may attempt to
tweak or change settings to "customise" them, without fully
understanding the impact.

Fix Description: Distinguish common options from developer-only
advanced options in the template with the --advanced flag.

fixes: #4361

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

**Review by droideck — APPROVED** [review]
Looks good to me!
But one small thing - Could you please change the commit header and PR's name to something like:
`Ticket 4361 - New Feature - add --advanced flag to dscreate` or `Ticket 4361 - RFE - add --advanced flag to dscreate`.

The reason is that I think we should keep our Changelog clean and descriptive so the information that the commit is an enchansment (even small) isn't lost.

What do you think?

**Comment by mreynolds389** [comment]
> Looks good to me!
> But one small thing - Could you please change the commit header and PR's name to something like:
> `Ticket 4361 - New Feature - add --advanced flag to dscreate` or `Ticket 4361 - RFE - add --advanced flag to dscreate`.
> 
> The reason is that I think we should keep our Changelog clean and descriptive so the information that the commit is an enchansment (even small) isn't lost.
> 
> What do you think?

Actually, everyone is doing something different with the header and I've been wanting to address it.  I'd prefer we use "Issue ####" and stop using "Ticket ####".  Most developers are using "Issue ###", but some are still using "Ticket" so I always have to tweak this when doing upstream builds and writing the release notes.

https://www.port389.org/docs/389ds/contributing.html#getting-the-patch-ready

I'll send an email out to the team about this as well.

**Comment by Firstyear** [comment]
It was because that was my git commit template, which I have now updated to be "Issue" at Mark's request. When I merge this I'll correct it to "issue". Is that all good?

**Comment by droideck** [comment]
> It was because that was my git commit template, which I have now updated to be "Issue" at Mark's request. When I merge this I'll correct it to "issue". Is that all good?

Also, please, change the commit header to something like:

```
Issue 4361 - New Feature - add --advanced flag to dscreate
or 
Issue 4361 - RFE - add --advanced flag to dscreate.
```

as it'll make our changelog cleaner and more descriptive so the information isn't lost that a commit is an enchantment (even small).

**Comment by Firstyear** [comment]
Done, if @mreynolds389 is around did you want to check the new subject line is okay?

**Comment by mreynolds389** [comment]
> Done, if @mreynolds389 is around did you want to check the new subject line is okay?

The current commit still has "Ticket", and your proposed revision is fine to me, but Simon's suggestion's are good.  It would be nice to see RFE in the header (for RFE's).  Makes reading the release notes more exciting (oh, hey, that's an RFE!)

**Comment by Firstyear** [comment]
> > Done, if @mreynolds389 is around did you want to check the new subject line is okay?
> 
> The current commit still has "Ticket", and your proposed revision is fine to me, but Simon's suggestion's are good. It would be nice to see RFE in the header (for RFE's). Makes reading the release notes more exciting (oh, hey, that's an RFE!)

I can update the commit msg when I merge, and it pulls from the current issue title :)

**Comment by Firstyear** [comment]
```   
   76d102d6e..cc2d47a12  389-ds-base-1.4.2 -> 389-ds-base-1.4.2
   99b40f983..160d44f3a  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
```

**Pull request merged**
