### PR TITLE
filter optimizer

### PR DESCRIPTION
**Pull request by mreynolds389**
Just testing Williams old filter optimization code, this is not ready for review.

### CODE REVIEW

**Comment by mreynolds389** [comment]
There is a regression with ACLsforn one-level scope searches.  This PR adds a parentid component to the filter (create_onelevel_filter() during build_candidate_list()), which in turn gets evaluated by the ACL code and causes regressions.

**Comment by Firstyear** [comment]
Okay, I'll see if I can investigate this today.

**Comment by mreynolds389** [comment]
> Okay, I'll see if I can investigate this today.

I think we just need to preserve the original filter and use that for ACI evaluation.  Because right now it adds parentId and objectclass filter components and those should be skipped from the access evaluation.

**Comment by Firstyear** [comment]
Yep, tottaly agree with you on that. I was going to see if we already preserved it, if not I'll add that to the pb.

**Comment by Firstyear** [comment]
See https://github.com/389ds/389-ds-base/pull/5171

**Pull request closed without merging**
