### PR TITLE
Backport missing Rust commits 

### PR DESCRIPTION
**Pull request by droideck**
Issue 5356 - Update Cargo.lock and bootstrap PBKDF2-SHA512 (#5480)
 Issue 5356 - For RUST build update the default password storage scheme
 Issue 4577 - Fix ASAN flags in specfile
 Issue 5046 - BUG - update concread (#5047)
 Issue 5043 - BUG - Result must be used compiler warning (#5045)
 Issue 4637 - ndn cache leak (#4724)
 Issue 4446 RFE - openldap password hashers
 Issue 4403 RFE - OpenLDAP pw hash migration tests (#4408)
 Issue 4410 RFE - ndn cache with arc in rust

### CODE REVIEW

**Comment by droideck** [comment]
It still misses something... Investigating.

**Comment by droideck** [comment]
@Firstyear hi, could you please check if I missed something obvious?

The pwdhash crashes like this:

```
Stack trace of thread 60275:
 #0  0x00005639eaf29902 main (pwdhash + 0x2902)
#1  0x00007ff7a2829510 __libc_start_call_main (libc.so.6 + 0x29510)
#2  0x00007ff7a28295c9 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x295c9)
#3  0x00005639eaf29ba5 _start (pwdhash + 0x2ba5)
ELF object binary architecture: AMD x86-64
```

Looks like it has problems getting the Rust password scheme versions:

```
(gdb) call (struct pw_scheme*)pw_name2scheme("DEFAULT")
$1 = (struct pw_scheme *) 0x0
(gdb) call (struct pw_scheme*)pw_name2scheme("PBKDF2_SHA256")
$2 = (struct pw_scheme *) 0x5555555bc660
(gdb) call (struct pw_scheme*)pw_name2scheme("PBKDF2-SHA256")
$3 = (struct pw_scheme *) 0x0
(gdb) call (struct pw_scheme*)pw_name2scheme("PBKDF2-SHA512")
$4 = (struct pw_scheme *) 0x0
```

I think all of the related commits are there but still...

**Comment by droideck** [comment]
Looks like `PBKDF2-` entries were missing from tempalte-dse.ldif.

Thanks, @mreynolds389, looks like it works now!

**Review by Firstyear — APPROVED** [review]
Hooray! This is great to see :)

**Review by mreynolds389 — APPROVED** [review]
LGTM!

**Pull request merged**
