### PR TITLE
Issue 6282 - BUG - out of tree build fails

### LINKED ISSUE #6282: Out of tree builds fail
When building with an external builddir, builds fail.

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: When building with an external builddir the build fails.

Fix Description: Due to how python setup.py works, we have to specifically template it into srcdir rather than the build dir.

Rename cargo/config to cargo/config.toml to avoid future build errors.

fixes: https://github.com/389ds/389-ds-base/issues/6282

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

**Review by vashirov — APPROVED** [review]
LGTM

**Comment by Firstyear** [comment]
@vashirov Any issues with this in 2.5? Seems like we need it there for SUSE.

**Comment by vashirov** [comment]
No issues, should be fine.

**Comment by Firstyear** [comment]
```
To github.com:389ds/389-ds-base.git
   a7deea8b3..161888969  389-ds-base-2.5 -> 389-ds-base-2.5
```
Thanks!

**Pull request merged**
