### PR TITLE
Issue 5561 - Nightly tests are still failing

### LINKED ISSUE #5561: Nightly tests are failing
**Issue Description**
Latest working job:
https://github.com/389ds/389-ds-base/actions/runs/3644095039/jobs/6153145448

First failing job:
https://github.com/389ds/389-ds-base/actions/runs/3653344884/jobs/6172866948

### PR DESCRIPTION
**Pull request by progier389**
Some python modules are missing to be able to run py.test CI
Added them back in .github/workflows/pytest.yml using dnf and pip

Issue: [5561](https://github.com/389ds/389-ds-base/issues/5561)

Reviewed by:

### CODE REVIEW

**Comment by progier389** [comment]
I suspect that someone has rebuild the test image and forgot to add some python modules
For now I propose to fix the issue by installing explicitly the modules before running py.test
We may want to fix the image and discard these changes later on.

**Review by droideck — COMMENTED** [review]
@progier389 it's pretty straightforward to update the image, actually. You just need to make a change in this file and merge - https://github.com/389ds/ci-images/blob/main/Containerfile.test

But... I see that the docker file already has python-slugify and the rest. I'm not sure why it's failing there... I'll check tomorrow.

**Comment by vashirov** [comment]
> I suspect that someone has rebuild the test image and forgot to add some python modules For now I propose to fix the issue by installing explicitly the modules before running py.test We may want to fix the image and discard these changes later on.

ci-images are rebuilt nightly, I recently bumped the Fedora version to F37: https://github.com/389ds/ci-images/commit/c9e93e2481cb8bf55673187fe1d2a11f2769d00e 
As Simon pointed out, pip modules are installed in the container image during the build: https://github.com/389ds/ci-images/blob/d4fc4f6279efef8e1a5e1235b558244406da2f86/Containerfile.test#L15
See for example this build log: https://github.com/389ds/ci-images/actions/runs/3690748098/jobs/6248127701#step:4:1428


The issue is that pytest in F37 has `-s` in shebang, preventing local packages to be loaded:
```
[root@8fcf3dd5ee2d ds]# py.test -v dirsrvtests/tests/suites/basic/basic_test.py::test_basic_ops
ImportError while loading conftest '/workspace/ds/dirsrvtests/conftest.py'.
dirsrvtests/conftest.py:21: in <module>
    from slugify import slugify
E   ModuleNotFoundError: No module named 'slugify'


[root@8fcf3dd5ee2d ds]# python3
Python 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from slugify import slugify
>>>


[root@8fcf3dd5ee2d ds]# python3 -s
Python 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from slugify import slugify
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'slugify'


>>>
[root@8fcf3dd5ee2d ds]# head -n1 /usr/bin/py.test
#! /usr/bin/python3 -sP

[root@8fcf3dd5ee2d ds]# rpm -q python3-pytest
python3-pytest-7.1.3-1.fc37.noarch
```

This was not the case for pytest in F36:
```
[root@22ab075ce243 /]# head -n1 /usr/bin/py.test
#!/usr/bin/python3
[root@22ab075ce243 /]# rpm -q python3-pytest
python3-pytest-6.2.5-2.fc36.noarch
```

In fact it is a packaging bug https://bugzilla.redhat.com/show_bug.cgi?id=2152171
It's fixed in the latest version:
```
[root@8fcf3dd5ee2d ds]# head -n1 /usr/bin/py.test
#! /usr/bin/python3 -P
[root@8fcf3dd5ee2d ds]# rpm -q python3-pytest
python3-pytest-7.1.3-2.fc37.noarch
```

I provided karma to the update: https://bodhi.fedoraproject.org/updates/FEDORA-2022-a174e00184
I encourage you do the same (only 1 more is needed to push it to stable).
And I've added a temporary workaround to the container image: https://github.com/389ds/ci-images/commit/a878209b984fc97e3420ebf6d1d26f7a141f7325
Tests looks greener now: https://github.com/389ds/389-ds-base/actions/runs/3699965510/jobs/6271272898

**Comment by droideck** [comment]
> I provided karma to the update: https://bodhi.fedoraproject.org/updates/FEDORA-2022-a174e00184
> I encourage you do the same (only 1 more is needed to push it to stable).

Done.

Thank you so much, Viktor!

**Pull request closed without merging**
