### PR TITLE
Issue 4646 - CLI/UI - revise DNA plugin management

### PR DESCRIPTION
**Pull request by mreynolds389**
Bug Description:

There was a false assumption that you have to create the shared DNA
server configuration entry, but in fact the server creates and manages
this entry.  The only thing you should edit in this entry are the
remote Bind Method and Connection Protocol.

Fix Description:

Remove the options to create the shared config entry, and edit the
core/reserved attributes.

Also fixed some issues where we were not showing CLI plugin output in
proper JSON.  This required some changes to the UI as well.

Relates: https://github.com/389ds/389-ds-base/issues/4646

### CODE REVIEW

**Comment by droideck** [comment]
I probably miss something... But the docs say that admin should add dnaSharedConfig (it was like that for RHDS 10)
https://access.redhat.com/documentation/en-us/red_hat_directory_server/10/html-single/administration_guide/index#dna-syntax

and I also see the same pattern across our tests.

Probably, the fact has changed at some point... If you can easily look it up, could you please share the version/the point where it has changed?

**Comment by mreynolds389** [comment]
> I probably miss something... But the docs say that admin should add dnaSharedConfig (it was like that for RHDS 10)
> https://access.redhat.com/documentation/en-us/red_hat_directory_server/10/html-single/administration_guide/index#dna-syntax
> 
> and I also see the same pattern across our tests.
> 
> Probably, the fact has changed at some point... If you can easily look it up, could you please share the version/the point where it has changed?

I think the docs have been wrong for a very long time (I just filed a doc bug: https://bugzilla.redhat.com/show_bug.cgi?id=1931582).  It's a just confusing setup.  The server definitely creates the shared config subentries automatically.   And it maintains the remaining values, etc.  So we should not have the ability to alter it except for the new remote settings.

I also checked FreeIPA, they also do not create those subentries but they use them.

**Comment by mreynolds389** [comment]
This reminds me, there are other problems with the DNA CLI.  Listing shared config entries only shows the first RDN, not the port.  So you can not use these "list" values for "showing" the entry.  Basically the list is useless.  I think maybe the CLI should be changed to use a single positional arg "HOSTNAME:PORT" instead of two separate positional arguments "HOSTNAME" and "PORT").  Either way I need to fix the "listing" to include the port, but what are your thoughts on changing the positional args?

**Comment by droideck** [comment]
> > I probably miss something... But the docs say that admin should add dnaSharedConfig (it was like that for RHDS 10)
> > https://access.redhat.com/documentation/en-us/red_hat_directory_server/10/html-single/administration_guide/index#dna-syntax
> > and I also see the same pattern across our tests.
> > Probably, the fact has changed at some point... If you can easily look it up, could you please share the version/the point where it has changed?
> 
> I think the docs have been wrong for a very long time (I just filed a doc bug: https://bugzilla.redhat.com/show_bug.cgi?id=1931582). It's just a confusing setup. The server definitely creates the shared config subentries automatically. And it maintains the remaining values, etc. So we should not have the ability to alter it except for the new remote settings.
> 
> I also checked FreeIPA, they also do not create those subentries but they use them.

Okay, got it!

> This reminds me, there are other problems with the DNA CLI. Listing shared config entries only shows the first RDN, not the port. So you can not use these "list" values for "showing" the entry. Basically the list is useless. I think maybe the CLI should be changed to use a single positional arg "HOSTNAME:PORT" instead of two separate positional arguments "HOSTNAME" and "PORT"). Either way I need to fix the "listing" to include the port, but what are your thoughts on changing the positional args?

I wonder if we can (and somebody does) specify the entry like this with dnaSecurePortNum:

    dnaHostname=host_name+dnaSecurePortNum=port_number,ou=ranges,dc=example,dc=com
    
If it's not a practice, I think 'hostname:port' looks good.

**Comment by mreynolds389** [comment]
> > This reminds me, there are other problems with the DNA CLI. Listing shared config entries only shows the first RDN, not the port. So you can not use these "list" values for "showing" the entry. Basically the list is useless. I think maybe the CLI should be changed to use a single positional arg "HOSTNAME:PORT" instead of two separate positional arguments "HOSTNAME" and "PORT"). Either way I need to fix the "listing" to include the port, but what are your thoughts on changing the positional args?
> 
> I wonder if we can (and somebody does) specify the entry like this with dnaSecurePortNum:
> 
> ```
> dnaHostname=host_name+dnaSecurePortNum=port_number,ou=ranges,dc=example,dc=com
> ```

Checking the DNA source code, we only use the dnaPortNum for constructing the DN of the sub-entries it creates.  But if someone created their own entry using dnaSecurePortNum it would still work.  But I think only FreeIPA really uses DNA so the risk is minimal, and it would only impact CLI/UI - not the actual plugin functionality.

**Comment by mreynolds389** [comment]
Made a few more changes, and even fixed a crash in dna when you misconfigure the remote bind & conn protocol.  Please review..

**Review by droideck — APPROVED** [review]
Looks good to me!

**Pull request merged**
