### PR TITLE
Issue 4169 - UI - Migrate Server, Security, and Schema tables to PF4

### PR DESCRIPTION
**Pull request by mreynolds389**
Description:  

Migrate these tables to PF4 tables.   Also added spinning buttons.

relates: https://github.com/389ds/389-ds-base/issues/4169

### CODE REVIEW

**Comment by droideck** [comment]
When I click **'Security Settings -> Certificate Management -> TLS Certificates -> Edit Trust Flags (on the cert)'** - The UI throughs an error:

```
Uncaught TypeError: Cannot read property '0' of undefined
    at o.value (index.js:117)
    at onClick (index.js:117)
    at Lb.onSelect (index.js:113)
    at onClick (index.js:113)
    at onClick (index.js:113)
    at Object.s (index.js:59)
    at f (index.js:59)
    at index.js:59
    at y (index.js:59)
    at it (index.js:59)
```

**Comment by droideck** [comment]
In 'SASL Settings' - Refresh button is not responsive.

And when I edit an item in SASL Mappings table - it doesn't update the list (so if I want to see the change I've maid - I need to refresh the whole UI with F5)

**Comment by droideck** [comment]
In the 'Schema' tab, the search doesn't work. If I try to type something, it fails with the following error:

```
Uncaught TypeError: i.may.toLowerCase is not a function
    at n.value (index.js:117)
    at onChange (index.js:113)
    at Object.s (index.js:59)
    at f (index.js:59)
    at index.js:59
    at y (index.js:59)
    at it (index.js:59)
    at Array.forEach (<anonymous>)
    at rt (index.js:59)
    at st (index.js:59)
```

**Comment by droideck** [comment]
Also, a minor issue, when I try to edit **'Trusted Certificate Authorites'** table entry, it says that everything is okay but it doesn't update some of the flags or it does something unexpected without any explanation:

Case 1
1. Click 'Edit Trust Flags';
2. Click on the checkboxes under 'Object Signing' column '(C) - Trusted CA' and '(T) - Trusted CA Client Auth' flags;
3. Click 'Save'; 
4. Click 'Edit Trust Flags' once again - under 'Object Signing' column - only '(C) - Trusted CA' is checked but  '(T) - Trusted CA Client Auth' is not checked.

Case 2
1. Click 'Edit Trust Flags';
2. Click on the checkboxes under 'Object Signing' column '(T) - Trusted CA Client Auth' flag;
3. Click 'Save';
4. Click 'Edit Trust Flags' once again - under 'Object Signing' column  - '(T) - Trusted CA Client Auth' is not checked but '(c) - Valid CA' is checked.

**Comment by mreynolds389** [comment]
Changes made, please review!

About the certificate trust flag issues.  certutil/NSS ignores certain combinations of the flags.  I don't know the details about why some flags are incompatible with others, but it is NSS ignoring/changing some of the flags.

**Comment by droideck** [comment]
If I modify Trusted CA certificate (removing C and T flags) it gives me a warning modal window (which is good) but this modal window is not closed automatically after I confirm.

**Comment by droideck** [comment]
'Matching Rules' search still gives an error.

**Comment by mreynolds389** [comment]
> If I modify Trusted CA certificate (removing C and T flags) it gives me a warning modal window (which is good) but this modal window is not closed automatically after I confirm.
> 
> 'Matching Rules' search still gives an error.

Sorry I didn't know MR was broken.  Anyway it's all fixed now...

**Review by droideck — APPROVED** [review]
Awesome!
You have my ack :)

**Pull request merged**
