### PR TITLE
Issue 3996 - Add dsidm rename option

### LINKED ISSUE #3996: dsidm doesn't support modrdn
Cloned from Pagure issue: https://pagure.io/389-ds-base/issue/50943
- Created at 2020-03-09 12:33:59 by [vashirov](https://pagure.io/user/vashirov) (@vashirov)
- Assigned to nobody
- Associated bugzillas
  - https://bugzilla.redhat.com/show_bug.cgi?id=1859218

---

#### Issue Description
`dsidm` can't change user's uid:

```
[root@server-f31 ds]# dsidm -y /root/dspw server-f31 user modify test replace:uid:test2
Error: Operation not allowed on RDN

[root@server-f31 ds]# dsidm -y /root/dspw server-f31 user modify test replace:dn:uid=test2,ou=People,dc=example,dc=com
Error: Object class violation - attribute "distinguishedName" not allowed

[root@server-f31 ds]# cat /var/log/dirsrv/slapd-server-f31/audit

time: 20200309112954
dn: uid=test,ou=people,dc=example,dc=com
result: 67
changetype: modify
replace: uid
uid: test2
-
replace: modifiersname
modifiersname: cn=directory manager
-
replace: modifytimestamp
modifytimestamp: 20200309112954Z
-

time: 20200309113018
dn: uid=test,ou=people,dc=example,dc=com
result: 65
changetype: modify
replace: distinguishedName
distinguishedName: uid=test2,ou=People,dc=example,dc=com
-
replace: modifiersname
modifiersname: cn=directory manager
-
replace: modifytimestamp
modifytimestamp: 20200309113018Z
-

```

#### Package Version and Platform
389-ds-base-1.4.2.8-3.fc31.x86_64

### LINKED ISSUE #4127: lib389 Issue: With Accounts/Account module delete fuction is not working
Cloned from Pagure issue: https://pagure.io/389-ds-base/issue/51074
- Created at 2020-05-07 07:03:04 by [aborah](https://pagure.io/user/aborah) (@aborah-sudo)
- Assigned to nobody
- Associated bugzillas
  - https://bugzilla.redhat.com/show_bug.cgi?id=1859215

---

Try to create some user with either UserAccounts Or Accounts Or try to generate users with dbgen . Then try to delete them with Accounts. 

Here some entries with specific ObjectClass  cant be loaded with UserAccounts but same  can be loaded with Accounts . In my test script while using Accounts/Account to load the entries generated by dbgen i am not able to delete them.

But the entries which can be loaded by UserAccounts/UserAccount can be deleted . That means delete function is working with  UserAccounts/UserAccount but not working with Accounts/Account.

### PR DESCRIPTION
**Pull request by droideck**
Description: Add rename option to dsidm CLI.
user, group, posixgroup, organizationalunit - rename by rdn.
account, role - rename by dn.
Set Account._protected = False by default so we can run
rename and delete operations.

Reviewed by: ?

Fixes: #4127 
Fixes: #3996

### CODE REVIEW

**Review by mreynolds389 — COMMENTED** [review]
Looks like this is missing "newsuperior" option for modrdn - for moving the entry to a different subtree

**Comment by droideck** [comment]
> Looks like this is missing "newsuperior" option for modrdn - for moving the entry to a different subtree

It is intentional as we want to be consistent with the rest of the CLI we have.

`dsidm - user, group, organizationalunit,  posixgroup` - are used for the certain subtrees where `dsidm` user should locate his users, ous, groups, etc. It is defined by `-b basedn` argument and (sometimes) implicit RDN (`ou=People, ou=Groups`).

```
dsidm localhost user rename user1 user2
```
    
`dsidm - account` - and if the user would like to move any IDM entry, he will use this subcommand as it allows to rename/modify/delete any Account entry. And it is done by just specifying `new and old` DNs.

```
dsidm localhost account rename uid=user1,dc=example,dc=com uid=user2,dc=example,dc=com
dsidm localhost account rename uid=user1,dc=example,dc=com uid=user1,o=redhat
```

**Review by mreynolds389 — APPROVED** [review]
Works for me.  Good job!  Ack

**Comment by Firstyear** [comment]
Yeah agreed, this looks good. Thanks @droideck you have my ack too :)

**Pull request merged**
