### PR TITLE
Issue 5941 - Switch default backend to lmdb and change version to 3.0

### PR DESCRIPTION
**Pull request by progier389**
Changes:
   [1] use lmdb by default 
   [2] Change version number to 3.0.0
   
Issue: #5941 

Reviewed by: @droideck, @tbordaz (Thanks!)

### CODE REVIEW

**Comment by progier389** [comment]
FYI: I plan to merge that one next year to 
  - avoid doing a major change just before Christmas break! -;)
  - start the nightly freeipa tests on Fedora 40 as soon as possible.

**Review by droideck — APPROVED** [review]
The change is straightforward and looks good to me.
You have my ack if the CI passes after #6035 rebase! (except the usual web test failures)

**Comment by progier389** [comment]
Rebased to main

**Comment by progier389** [comment]
Waiting for the CI tests result - These days only webui should fails (and the random failures due to dnf race condition)

**Review by tbordaz — APPROVED** [review]
LGTM. True pleasure to click 'Approve' on this PR ;)

**Pull request merged**
