### PR TITLE
Issue 4169 - UI - migrate modals to PF4

### PR DESCRIPTION
**Pull request by mreynolds389**
Description:  

Updated the Modals to PF4.  Also had to redesign DNA and Managed Entry plugin pages.  Other minor improvements were made.

Relates: https://github.com/389ds/389-ds-base/issues/4169

### CODE REVIEW

**Comment by droideck** [comment]
If we go to - Server Settings -> Security -> Certificate Management -> Trusted Certificate Authorite, the "Add" modal there looks like this:
edit-trust-flags

It's good but the alignment there is a bit odd...

**Comment by droideck** [comment]
Also, I can't check all of the functionality for Schema as your change c25d385f169e4f4dcb6caec9edf71f3235ced447 is not in this branch.
Could you please rebase onto master?

**Comment by mreynolds389** [comment]
> Also, I can't check all of the functionality for Schema as your change [c25d385](https://github.com/389ds/389-ds-base/commit/c25d385f169e4f4dcb6caec9edf71f3235ced447) is not in this branch.
> Could you please rebase onto master?

Done and thanks for reviewing.  I have more UI PR's I have not even released yet, but I'll do that after this one is reviewed and merged.

**Comment by mreynolds389** [comment]
Revised the trust flag modal, but really I want to fix these alignment issues when we go from PF 3 Forms to PF4 grids/forms.

**Comment by droideck** [comment]
I found one odd issue with Schema tab...

1. Click the checkbox 'Only Non-standard Schema'
2. Then click 'Add Objectclass' and type something in `Objectclass Name` field

In the result, the list in the background is updated and it starts to show 'Standard Schema' even though the Checkbox is checked.

> Revised the trust flag modal, but really I want to fix these alignment issues when we go from PF 3 Forms to PF4 grids/forms.

Sure! Np:)

**Comment by mreynolds389** [comment]
> I found one odd issue with Schema tab...
> 
>     1. Click the checkbox 'Only Non-standard Schema'
> 
>     2. Then click 'Add Objectclass' and type something in `Objectclass Name` field
> 
> 
> In the result, the list in the background is updated and it starts to show 'Standard Schema' even though the Checkbox is checked.

 Ok I'll check this out...

**Comment by mreynolds389** [comment]
> > I found one odd issue with Schema tab...
> > ```
> > 1. Click the checkbox 'Only Non-standard Schema'
> > 
> > 2. Then click 'Add Objectclass' and type something in `Objectclass Name` field
> > ```
> > 
> > 
> > In the result, the list in the background is updated and it starts to show 'Standard Schema' even though the Checkbox is checked.
> 
> Ok I'll check this out...

Ok, this was how it always worked, not a regression from this PR, but I fixed it anyway.  :-)  Please review...

**Review by droideck — APPROVED** [review]
Thanks! Impressive rework PR!
LGTM!

**Pull request merged**
