### PR TITLE
Remove stale libevent(-devel) dependency

### PR DESCRIPTION
**Pull request by Flowdalic**
It appears that the last user of libevent disappeared with
44e92dc8b900 ("Ticket 50669 - remove nunc-stans").

### CODE REVIEW

**Comment by Firstyear** [comment]
I think we are working to re-include libevent soon, so maybe we might leave this one ....

**Comment by Flowdalic** [comment]
> I think we are working to re-include libevent soon, so maybe we might leave this one ....

Well,. or just revert the commit once you re-introduce libevent in 389ds? The main issue right now is `PKG_CHECK_MODULES([EVENT], [libevent])`, which means you can't build 389ds without libevent being present (or without patching this line out).

**Comment by Flowdalic** [comment]
Ping. I just ran into this again when bumping 389-ds-base in Gentoo.

**Comment by mreynolds389** [comment]
> Ping. I just ran into this again while bumping 389-ds-base in Gentoo.

Sorry we were going to actually use it for epoll() but that work is indefinitely stalled, so we can back this out for now...

**Review by mreynolds389 — APPROVED** [review]

**Comment by mreynolds389** [comment]
@Flowdalic - do you need this in earlier versions?  Or is "main" fine?

**Pull request merged**
