### PR TITLE
Issue 4791 - Missing dependency for RetroCL RFE

### LINKED ISSUE #4791: Workaround for RetroCL exclude attrs missing dependency
**Issue Description**
The RetroCL exclude attribute RFE is dependent on the functionality of  a EntryUUID bug fix that didn't make into the latest build.  This breaks the RetroCL change so we need to provide a workaround.

RetroCL RFE 
https://github.com/389ds/389-ds-base/pull/4723

EntryUUID
https://github.com/389ds/389-ds-base/issues/4224

**Affected branches:**
 - 389-ds-base-1.4.3
 - 389-ds-base-1.4.4

**Steps to Reproduce**
1. Go 389-ds-base-1.4.3 branch
2. Run retrocl CI test - sudo pytest -s -v dirsrvtests/tests/suites/retrocl/basic_test.py
3. See error detailing missing dependency

**Expected results**
The retrocl CI test should pass

### PR DESCRIPTION
**Pull request by jchapma**
Description: The RetroCL exclude attribute RFE is dependent on functionality of the
	     EntryUUID bug fix, that didn't make into the latest build. This breaks the
             RetroCL exclude attr feature so we need to provide a workaround.

Fixes: https://github.com/389ds/389-ds-base/issues/4791

Relates: https://github.com/389ds/389-ds-base/pull/4723

Relates: https://github.com/389ds/389-ds-base/issues/4224

Reviewed by: ?

### CODE REVIEW

**Review by tbordaz — COMMENTED** [review]
LGTM
2 CI failures are due #4379 (fixed) and #4764 (under investigation).
@jchapma did you test that this patch works in 1.4.3 ?

**Comment by jchapma** [comment]
> LGTM
> 2 CI failures are due #4379 (fixed) and #4764 (under investigation).
> @jchapma did you test that this patch works in 1.4.3 ?

**Comment by jchapma** [comment]
> LGTM
> 2 CI failures are due #4379 (fixed) and #4764 (under investigation).
> @jchapma did you test that this patch works in 1.4.3 ?

I tested this change on 1.4.3 and master.

**Review by droideck — APPROVED** [review]
LGTM too!

Also, @jchapma @tbordaz - I am not sure why but the tests are not run in the PR CI.
They are 'deselected'.

**Comment by jchapma** [comment]
389-ds-base-1.4.3 -> d5896fb43695c3db32505fd29253f28791d396c4

**Pull request merged**
