### PR TITLE
Issue 4169 - UI - Migrate alerts to PF4

### PR DESCRIPTION
**Pull request by mreynolds389**
Description:  

Migrate the toast notifications to PF4 Alerts.

Also fixed a refresh problem on the Tuning page.

relates: https://github.com/389ds/389-ds-base/issues/4169

### CODE REVIEW

**Review by droideck — COMMENTED** [review]
I wonder if it'd be possible to make it properly 'hover'...

Because now the alerts are always displayed on the same level. Because of this, sometimes you can't read alert (check my back up screenshot - the 'successful alert' is displayed in the gray area behind), and also it's impossible to read 'instance menu' if there are some alerts (but I think this part was like that even before the PR)

**Comment by droideck** [comment]
Screenshot from 2021-02-22 15-11-28
Screenshot from 2021-02-22 15-12-28

**Comment by mreynolds389** [comment]
> I wonder if it'd be possible to make it properly 'hover'...

Fixed

> also it's impossible to read 'instance menu' if there are some alerts (but I think this part was like that even before the PR)

Yeah its always been that way, not sure what you would prefer instead.  The alerts should timeout, or can be closed.

**Comment by droideck** [comment]
> > I wonder if it'd be possible to make it properly 'hover'...
> 
> Fixed
> 
> > also it's impossible to read 'instance menu' if there are some alerts (but I think this part was like that even before the PR)
> 
> Yeah its always been that way, not sure what you would prefer instead. The alerts should timeout, or can be closed.

I imagine that ideally when this sequence of events happens:
1. Alert is displayed
2. I click on the 'Instance' menu button (where Restart, Stop, etc.)

Then the 'Instance' menu is displayed above the alert as it has happened later.

**Review by droideck — APPROVED** [review]
You have my ack as the issue I mentioned is really minor and it probably doesn't worth the fuss.

**Pull request merged**
