### PR TITLE
Issue 5203 - outdated version in provided metadata for lib389

### LINKED ISSUE #5203: [lib389] outdated version in provided metadata
**Issue Description**

There is a hardcoded version of `lib389` since 9dccfea39a2e0477cdad5463eb4ad4a25ac7ad68.

**Package Version and Platform:**
 - Platform: any
 - Package and version: 1.4.0.2 +

**Steps to Reproduce**
```python
>>> from importlib.metadata import version                                       
>>> version("lib389")                                                            
'1.4.0.1'
```

**Expected results**
Expected actual version of `lib389`.

### PR DESCRIPTION
**Pull request by stanislavlevin**
Bug Description:

There is a hardcoded version of `lib389` since
9dccfea39a2e0477cdad5463eb4ad4a25ac7ad68.

Fix Description:

Build `setup.py` from template.

fixes: https://github.com/389ds/389-ds-base/issues/5203

### CODE REVIEW

**Comment by stanislavlevin** [comment]
rebased.

**Comment by droideck** [comment]
LGTM.

@mreynolds389 are you okay with the lib389 version change? (I don't want it to disturb our releases)

**Review by droideck — APPROVED** [review]
LGTM.

@mreynolds389 are you okay with the lib389 version change? (I don't want it to disturb our releases)

**Comment by mreynolds389** [comment]
> LGTM.
> 
> @mreynolds389 are you okay with the lib389 version change? (I don't want it to disturb our releases)

We need to verify this works in Fedora (koji), so a scratch should be done to test it.

**Comment by stanislavlevin** [comment]
@mreynolds389, @droideck, ^

**Comment by mreynolds389** [comment]
This is breaking our tooling for building tarballs (which is needed for all upstream and downstream builds that we do):


# TAG=389-ds-base-2.2.0 ; export $TAG ; SKIP_AUDIT_CI=1 make -f rpm.mk dist-bz2
...
...
make[1]: Leaving directory '/home/mareynol/source/delete/389-ds-base/src/cockpit/389-console'
mkdir -p src/cockpit/389-console/node_modules/webpack
touch -r src/cockpit/389-console/package.json src/cockpit/389-console/node_modules/webpack
tar cjf 389-ds-base-2.2.0.tar.bz2 --transform "s,^,389-ds-base-2.2.0/," $(git ls-files) vendor/ src/cockpit/389-console/cockpit_dist/ src/cockpit/389-console/node_modules
tar: src/lib389/Makefile: Cannot stat: No such file or directory
tar: src/lib389/VERSION: Cannot stat: No such file or directory
tar: src/lib389/setup.py: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
make: *** [rpm.mk:67: dist-bz2] Error 2

**Comment by vashirov** [comment]
> This is breaking our tooling for building tarballs (which is needed for all upstream and downstream builds that we do):

Did you test by applying the patch or by checking out the PR branch?
`git ls-files` lists checked in files, so if you applied the patch, but didn't commit the changes, `git ls-files` would still list the deleted files.

I tested from PR branch and it worked for me.

@stanislavlevin, could you please rebase your PR? Thanks.

**Comment by stanislavlevin** [comment]
rebased.

**Pull request merged**
