### PR TITLE
Issue 4775 - Add entryuuid CLI and Fixup

### LINKED ISSUE #4775: Add missing entryuuid cli
This was missed in the entryuuid feature addition, so we need this for dsconf.

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: EntryUUID when added was missing it's CLI
and helpers for fixups.

Fix Description: Add the CLI elements.

fixes: https://github.com/389ds/389-ds-base/issues/4775

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

**Comment by mreynolds389** [comment]
Fixup fails to run for me:

# dsconf localhost plugin entryuuid fixup -f objectclass=* dc=example,dc=com
Attempting to add task entry...
EntryUUID fixup task for %s has failed. Please, check logs

So there is a bug  here reporting the error...

Logs don't provide much help:

[21/May/2021:09:22:10.881267236 -0400] - ERR - plugins/entryuuid/src/lib.rs:187 - task_handler -> fixup complete, failed -> Unknown
[21/May/2021:09:22:10.885831138 -0400] - ERR - plugins/entryuuid/src/lib.rs:20 - entryuuid_plugin_task_thread => task error -> GenericFailure


I am testing this against 1.4.3, not sure if something else is missing on my part, but the error handler should still be fixed.

**Comment by mreynolds389** [comment]
I was not missing anything, turns out if you add a filter to the fixup task then things break...

**Comment by Firstyear** [comment]
> I was not missing anything, turns out if you add a filter to the fixup task then things break...

I can't reproduce this mate,  what filter are you trying to add?

**Comment by mreynolds389** [comment]
> > I was not missing anything, turns out if you add a filter to the fixup task then things break...
> 
> I can't reproduce this mate, what filter are you trying to add?

# dsconf localhost plugin entryuuid fixup -f objectclass=* dc=example,dc=com

I also tried objectclass=top

**Comment by Firstyear** [comment]
I've just used both and it works. Can you try '(objectClass=*)' ?

**Comment by Firstyear** [comment]
Yeah, it's the lack of '(' and ')' in the filter. This string is being passed directly into slapi_search_internal_set_pb_ext() which means likely it's just a 'feature' of the slapi api that it needs the outer ().

**Comment by mreynolds389** [comment]
> Yeah, it's the lack of '(' and ')' in the filter. This string is being passed directly into slapi_search_internal_set_pb_ext() which means likely it's just a 'feature' of the slapi api that it needs the outer ().

Would it be too much to ask that the CLI or rust code adds the parenthesis if they are missing?  I don't think we require the parenthesis for other filters used by other DS CLI subcommands.  Just looking for consistency...

**Comment by Firstyear** [comment]
I think if we are going to add this, it would be in the rust code. It's not too much to ask, I'll get it done today/tomorrow

**Comment by Firstyear** [comment]
@mreynolds389 This fixes the filter-without-brace behaviour.

**Comment by mreynolds389** [comment]
Ack

**Pull request merged**
