### PR TITLE
Issue 5383 - UI - Various fixes and RFE's for UI

### PR DESCRIPTION
**Pull request by mreynolds389**
Description:

Addressing these bugs/RFEs found during our testing day:

https://bugzilla.redhat.com/show_bug.cgi?id=2090687 - RFE - Add attribute search box when editing/adding user
https://bugzilla.redhat.com/show_bug.cgi?id=2090460 - can not do modrdn
https://bugzilla.redhat.com/show_bug.cgi?id=2090069 - stopping instance does not display message
https://bugzilla.redhat.com/show_bug.cgi?id=2090393 - no warning when setting port to zero
https://bugzilla.redhat.com/show_bug.cgi?id=2095765 - enabling disabling logs
https://bugzilla.redhat.com/show_bug.cgi?id=2090475 - unable edit trust flags of CA
https://bugzilla.redhat.com/show_bug.cgi?id=2090449 - numeric log levels not displayed
https://bugzilla.redhat.com/show_bug.cgi?id=2090403 - monitor causes too many messages in console
https://bugzilla.redhat.com/show_bug.cgi?id=2090499 - selecting index type before selecting attribute...
https://bugzilla.redhat.com/show_bug.cgi?id=2090152 - attribute encryption
https://bugzilla.redhat.com/show_bug.cgi?id=2090140 - Selecting and deselecting "Reindex Attribute After Saving"
https://bugzilla.redhat.com/show_bug.cgi?id=2029839 - can not enable dict checks

relates: https://github.com/389ds/389-ds-base/issues/5383

Reviewed by: ?

### CODE REVIEW

**Comment by droideck** [comment]
If I edit an Index (Suffix - Indexes - Three Dots) and if I click on "Reindex Attribute After Saving" option and then uncheck it. Save button is still active (but it should be disabled as there's nothing worth saving)

**Review by droideck — APPROVED** [review]
Besides the minor issue, looks good to me!

**Comment by mreynolds389** [comment]
> Besides the minor issue, looks good to me!

Fixed!

**Comment by mreynolds389** [comment]
> If I edit an Index (Suffix - Indexes - Three Dots) and if I click on "Reindex Attribute After Saving" option and then uncheck it. Save button is still active (but it should be disabled as there's nothing worth saving)
> 
> P.S. https://bugzilla.redhat.com/show_bug.cgi?id=2090140 - Selecting and deselecting "Reindex Attribute After Saving"

Fixed!

**Pull request merged**
