### PR TITLE
Issue 4379 - Allow more than 1 empty AttributeDescription for ldapsea…

### PR DESCRIPTION
**Pull request by aadhikar**
…rch, without the risk of denial of service

Desciption: Added a test case to verify up to 10 empty values and a negetive
case to check max limit.

Relates: https://github.com/389ds/389-ds-base/issues/4379

Reviewed by: ???

### CODE REVIEW

**Review by bsimonova — APPROVED** [review]
I see only typo in Description in commit message and "Should succeed" in expected results but otherwise LGTM!

**Comment by bsimonova** [comment]
Ok, I see there is an issue in checks and I can confirm the test fails for me with ldap.SERVER_DOWN when it is ran together with other tests. It works individually. This should be investigated further.

**Review by bsimonova — CHANGES_REQUESTED** [review]
Please investigate why the test fails when run together with other tests, maybe it needs to be in separate file.

**Comment by aadhikar** [comment]
@bsimonova Thanks for your investigation, test_ldbm_modification_audit_log is making the test fail.

**Review by bsimonova — APPROVED** [review]
LGTM!

**Review by droideck — APPROVED** [review]
LGTM too!

**Pull request merged**
