### PR TITLE
Issue 4446 RFE - openldap password hashers

### LINKED ISSUE #4446: OpenLDAP password hashers
As we want to support openldap to 389 migration, this means we need to support importing hashes from OpenLDAP. OpenLDAP supports a number of crypto types we do not, and some in formats in userPassword that differ from ours.

The main types are:

* PBKDF2
* PBKDF2-SHA1
* PBKDF2-SHA256
* PBKDF2-SHA512
* ARGON2

Thankfully for us there are no name conflicts here! Our pbkdf2 variant uses `PBKDF2_SHA256` (_ not -). 

As tested in #4403 all other password types known to OpenLDAP are supported (excluding customised overlays, which we would not support anyway).

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: To allow easier migrations, we need to support
some password types that OpenLDAP has that we do not. This
is mainly PBKDF2 types. OpenLDAP's hashers are
based on python passlib, so they also store the values in
a different way than our PBDKF2 module.

Fix Description: This adds passlib style PBKDF2 support, written
in Rust. It extends the slapi_r_plugin shim to support password
extensions for Rust plugins, as well as providing a number of
small improvements to the build system and testing for rust
plugins.

fixes: #4446 

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

**Comment by mreynolds389** [comment]
How are the plugin init functions called?  I don't see any functions like:  pwdchan_pbkdf2_plugin_init() in your patch.

**Comment by Firstyear** [comment]
> How are the plugin init functions called? I don't see any functions like: pwdchan_pbkdf2_plugin_init() in your patch.

This is described in https://github.com/389ds/389-ds-base/blob/master/src/slapi_r_plugin/README.md

The short summary is that the interfaces are generated in the macro call `slapi_r_plugin_hooks!(pwdchan_pbkdf2, PwdChanPbkdf2);` which then expands these tokens in slapi_r_plugin/src/macros.rs, for example, https://github.com/389ds/389-ds-base/pull/4457/files#diff-f7031593fccd94198d88423fd773c93a4d652cbef5c092e6fbf55f1f2455c83eR269 which is the pw encrypt hook. The _init() hook already existed from the entryuuid work. These landing sites do the unsafe C <-> rust conversions so that the plugin is only implemented in terms of safe rust code.

hope that explains it.

**Comment by Firstyear** [comment]
@mreynolds389 the pushed update adds some extended testing in tests and adds a check for a django pbkdf2 hash which is very similar to the openldap one.

**Comment by mreynolds389** [comment]
Getting rust compiler warnings:

```
     Running `rustc --crate-name slapi_r_plugin --edition=2018 slapi_r_plugin/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type staticlib --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C metadata=c6cd4901df9f7950 -C extra-filename=-c6cd4901df9f7950 --out-dir /home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/rs/release/deps -L dependency=/home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/rs/release/deps --extern lazy_static=/home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/rs/release/deps/liblazy_static-12524c167939ffb1.rlib --extern libc=/home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/rs/release/deps/liblibc-1d4ae733568063af.rlib --extern paste=/home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/rs/release/deps/libpaste-ad1c1e8dcbbb16d2.rlib --extern uuid=/home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/rs/release/deps/libuuid-3e95662f22ea8f77.rlib -L native=/home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/ -l dylib=slapd`
warning: unused `#[macro_use]` import
 --> slapi_r_plugin/src/lib.rs:1:1
  |
1 | #[macro_use]
  | ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `DerefMut`
 --> slapi_r_plugin/src/modify.rs:9:23
  |
9 | use std::ops::{Deref, DerefMut};
  |                       ^^^^^^^^


libtool: link: gcc -shared  -fPIC -DPIC  ldap/servers/plugins/acl/.libs/libacl_plugin_la-acl.o ldap/servers/plugins/acl/.libs/libacl_plugin_la-acl_ext.o ldap/servers/plugins/acl/.libs/libacl_plugin_la-aclanom.o ldap/servers/plugins/acl/.libs/libacl_plugin_la-acleffectiverights.o ldap/servers/plugins/acl/.libs/libacl_plugin_la-aclgroup.o ldap/servers/plugins/acl/.libs/libacl_plugin_la-aclinit.o ldap/servers/plugins/acl/.libs/libacl_plugin_la-acllas.o ldap/servers/plugins/acl/.libs/libacl_plugin_la-acllist.o ldap/servers/plugins/acl/.libs/libacl_plugin_la-aclparse.o ldap/servers/plugins/acl/.libs/libacl_plugin_la-aclplugin.o ldap/servers/plugins/acl/.libs/libacl_plugin_la-aclutil.o   -Wl,-rpath -Wl,/home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/.libs -Wl,-rpath -Wl,/usr/lib64/dirsrv -L/home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/.libs ./.libs/libslapd.so -lgcc_s -lc -lm ./.libs/libns-dshttpd.so /home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/.libs/libldaputil.so /home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/.libs/libslapd.so -lssl -lcrypto -lkrb5 -lk5crypto -lcom_err -lpcre -lsystemd /home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/.libs/libsds.so /home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/.libs/libsvrcore.so -lcrack -lrt -lutil -lsasl2 -lssl3 -lsmime3 -lnss3 -lnssutil3 -lldap_r -llber -lplds4 -lplc4 -lnspr4 -lpthread -ldl -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -g -O2 -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -O2 -g -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld   -Wl,-soname -Wl,libacl-plugin.so -o .libs/libacl-plugin.so
warning: field is never read: `be`
  --> slapi_r_plugin/src/backend.rs:50:5
   |
50 |     be: BackendRef,
   |     ^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `pin`
 --> slapi_r_plugin/src/charray.rs:7:5
  |
7 |     pin: Vec<CString>,
  |     ^^^^^^^^^^^^^^^^^

warning: field is never read: `pb`
  --> slapi_r_plugin/src/modify.rs:81:5
   |
81 |     pb: Pblock,
   |     ^^^^^^^^^^

warning: field is never read: `pb`
  --> slapi_r_plugin/src/search.rs:56:5
   |
56 |     pb: Pblock,
   |     ^^^^^^^^^^

libtool: link: ( cd ".libs" && rm -f "libacl-plugin.la" && ln -s "../libacl-plugin.la" "libacl-plugin.la" )                                                                                                              
warning: 6 warnings emitted



Finished release [optimized] target(s) in 3.21s
cp /home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/rs/release/libentryuuid.a /home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/.libs/libentryuuid.a
       Fresh cfg-if v0.1.10
       Fresh ppv-lite86 v0.2.10
       Fresh lazy_static v1.4.0
       Fresh libc v0.2.80
       Fresh proc-macro-hack v0.5.19
       Fresh paste-impl v0.1.18
       Fresh paste v0.1.18
       Fresh getrandom v0.1.15
       Fresh rand_core v0.5.1
       Fresh rand_chacha v0.2.2
       Fresh rand v0.7.3
       Fresh uuid v0.8.1
       Fresh slapi_r_plugin v0.1.0 (/home/mareynol/source/389-backup/389-ds-base/rpmbuild/BUILD/389-ds-base-2.0.1.20201202git7d2f95dc5/src/slapi_r_plugin)
warning: unused `#[macro_use]` import
 --> slapi_r_plugin/src/lib.rs:1:1
  |
1 | #[macro_use]
  | ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `DerefMut`
 --> slapi_r_plugin/src/modify.rs:9:23
  |
9 | use std::ops::{Deref, DerefMut};
  |                       ^^^^^^^^

warning: field is never read: `be`
  --> slapi_r_plugin/src/backend.rs:50:5
   |
50 |     be: BackendRef,
   |     ^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `pin`
 --> slapi_r_plugin/src/charray.rs:7:5
  |
7 |     pin: Vec<CString>,
  |     ^^^^^^^^^^^^^^^^^

warning: field is never read: `pb`
  --> slapi_r_plugin/src/modify.rs:81:5
   |
81 |     pb: Pblock,
   |     ^^^^^^^^^^

warning: field is never read: `pb`
  --> slapi_r_plugin/src/search.rs:56:5
   |
56 |     pb: Pblock,
   |     ^^^^^^^^^^

warning: 6 warnings emitted
```

**Comment by Firstyear** [comment]
Nice to see you'll complain about rust warnings as much as C ones @mreynolds389 :) 

There is actually a flag we can enable in the rust code for deny-warnings which turns them all into errors to avoid this. I will enable it and clean these up.

**Comment by mreynolds389** [comment]
> Nice to see you'll complain about rust warnings as much as C ones @mreynolds389 :)

Indentation issues and compiler warnings are my jam!

**Comment by Firstyear** [comment]
> > Nice to see you'll complain about rust warnings as much as C ones @mreynolds389 :)
> 
> Indentation issues and compiler warnings are my jam!

You'll be happy (or disappointed) to know in rust that cargo fmt auto-indents and tidies, and we can deny warnings so they'll hopefully be much rarer.

**Comment by Firstyear** [comment]
@mreynolds389 Weird, I couldn't reproduce those errors myself, but I have updated the commit to add deny(warnings) which means any warning in tests or a build will cause it to fail. Maybe I forgot to push something in my branch? Anyway, have another look now :)

**Comment by Firstyear** [comment]
@mreynolds389 Turns out there was one warning in a single test but I've resolved that now. So hopefully this clears it all up for you!

**Comment by mreynolds389** [comment]
Build is clean, ack!

FYI, I saw those warnings by setting "RUST_ON" in rpm.mk and running:  make -f rpm.mk rpms

**Comment by Firstyear** [comment]
@mreynolds389 They shouldn't happen again since I have deny warnings now :) Thanks for the review mate! Do you have any objections to this being applied to 1.4.4 as well? We need it for a SUSE deliverable, but I'm also happy to maintain a seperate 1.4.4 maint branch for the features we need if we have to.

**Comment by mreynolds389** [comment]
> @mreynolds389 They shouldn't happen again since I have deny warnings now :) Thanks for the review mate! Do you have any objections to this being applied to 1.4.4 as well? 

Sure no problem.  Adjust the issue milestone too, thanks!

**Comment by Firstyear** [comment]
```
   99443d776..1063bb7d2  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
```

**Pull request merged**
