### PR TITLE
factory NSPR lock to pthread lock

### PR DESCRIPTION
**Pull request by tbordaz**
Issue 4600 - performance modify rate: reduce lock contention on the object extension factory

Bug description:
	object extension factory uses a simple mutex to protect allocation/destroy object.
	This mutex is a NSPR mutex. Using modrate load (entry object), the mutext is the
	second hottest contention. Moving it to pthread mutex moves it down to the fifth
	hotest.
	giving a small throughput benefit (1%)

Fix description:
	Use pthread normal mutex

relates: https://github.com/389ds/389-ds-base/issues/4600

Reviewed by:  ?

Platforms tested: RHEL 8.3 and F31

### CODE REVIEW

**Review by droideck — COMMENTED** [review]
Please, fix me if I'm wrong. But should we also change the type of `extension_lock` (make it `pthread_mutex_t`)?

**Comment by tbordaz** [comment]
oh !! absolutely right . Thanks for that catch. I will fix that.

**Review by droideck — APPROVED** [review]
LGTM!

**Comment by Firstyear** [comment]
Ack from me too

**Pull request merged**
