### PR TITLE
Issue 5512 - BUG - skip pwdPolicyChecker OC in migration

### LINKED ISSUE #5512: ppolicy migration from openldap fails in newer openldap schemas.
We also need to exclude pwdPolicyChecker objectClass

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: Unsupported as we don't support it's may attr types

Fix Description: Skip as it's incompatible.

fixes: https://github.com/389ds/389-ds-base/issues/5512

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

**Comment by Firstyear** [comment]
Will backport to 2.0 as well :)

**Comment by droideck** [comment]
LGTM!

**Comment by Firstyear** [comment]
@droideck Need you to click approve :)

**Review by droideck — APPROVED** [review]
Oops! Done)

**Comment by Firstyear** [comment]
```
   bd234df6b..0ebbb26f8  389-ds-base-2.2 -> 389-ds-base-2.2
   c745b44f5..8fdbe5947  389-ds-base-2.1 -> 389-ds-base-2.1
   2dbc5788b..d15a0a7f1  389-ds-base-2.0 -> 389-ds-base-2.0
   9af9f922c..136fc8448  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
```

**Pull request merged**
