### PR TITLE
Issue 4656 - Remove problematic language from UI/CLI/lib389

### PR DESCRIPTION
**Pull request by mreynolds389**
Description:  

Replace "master" and "slave" with more appropriate names

relates: https://github.com/389ds/389-ds-base/issues/4656

### CODE REVIEW

**Comment by elkris** [comment]
Hi Mark,
I think it is more than time to make these language changes and get rid of the master-slave pattern (which never was a correct description of the roles, no "master" would have looked at a "slave" as a identical copy of himself). But I am not sure if the new terminology is optimal. There are two different points of view, one is temporary in a replication session where one supplier updates a consumer, and in the next session the roles can be reversed. And then there is the distinction of "read only" and "updatable" replicas. master would have to be replaced by a term describing a replica which accepts updates - and I can't find a proper term, not in english, but also not in german.  If we can't find anything better the overall use of "supplier" should be fine, but it is not optimal.
And I have not checked all changes, but in full consequence even terms like MMR would have to be changed

**Comment by mreynolds389** [comment]
> Hi Mark,
> I think it is more than time to make these language changes and get rid of the master-slave pattern (which never was a correct description of the roles, no "master" would have looked at a "slave" as a identical copy of himself). But I am not sure if the new terminology is optimal. There are two different points of view, one is temporary in a replication session where one supplier updates a consumer, and in the next session the roles can be reversed. And then there is the distinction of "read only" and "updatable" replicas. master would have to be replaced by a term describing a replica which accepts updates - and I can't find a proper term, not in english, but also not in german. If we can't find anything better the overall use of "supplier" should be fine, but it is not optimal.
> And I have not checked all changes, but in full consequence even terms like MMR would have to be changed

Oh there are going to be a lot of changes related to this.  This is just phase one.  We still have the config, plugin entry, logging, source code, etc.  The current plan we came up with was from the Admin perspective, it's Supplier/Hub/Consumer, but internally it will be:  sender/receiver  - so this will be used in logging and other naming in the replication code.  We debated many many terms (readwrite/readwrite-hub/readonly,... etc, etc, etc), but we settled on Supplier/Hub/Consumer (exposed terminology) and  sender/receiver (internal terminology).  Sorry, I guess we should have made the discussion public on 389-devel list.

**Comment by Firstyear** [comment]
> discussion public on 389-devel list.

Yeeeeaaaaaaahhhhhh probably should have :) 

I still agree it's a change we need to make though - even on mailing lists I've been trying to avoid the M/S terminology.

**Comment by Firstyear** [comment]
Had a quick look and it's okay from me. Only thing to be careful of is that it may break some peoples CLI scripts but IMO our cli isn't api stable so it's not a problem to me.

**Comment by mreynolds389** [comment]
> Had a quick look and it's okay from me. Only thing to be careful of is that it may break some peoples CLI scripts but IMO our cli isn't api stable so it's not a problem to me.

Actually in 1.4.x I'm going to make it CLI backwards compatible, but in 2.x it needs to be removed.

**Comment by mreynolds389** [comment]
> > discussion public on 389-devel list.
> 
> Yeeeeaaaaaaahhhhhh probably should have :)
> 
> I still agree it's a change we need to make though - even on mailing lists I've been trying to avoid the M/S terminology.

To be honest, it was only a RHEL requirement, and I thought it was going to be straightforward without much debate.  Simple change...  then it did turn into a debate internally, and now externally :-)

**Comment by Firstyear** [comment]
> To be honest, it was only a RHEL requirement, and I thought it was going to be straightforward without much debate. Simple change... then it did turn into a debate internally, and now externally :-)

Hey, it's not a debate :) I think the change is good and should be done. No debate here at all, and thanks for putting in the hard work to achieve it!

I just would have liked upstream to be included from the start in the conversation. That's all. Especially as we have some more contributors who aren't inside RH it's good to have us all involved. 

But again. It looks like a good change to me, so ack here. Like anything I'm sure we'll hit a rough edge but we should do this.

**Pull request merged**
