### PR TITLE
bugfix for --passwd-file not working on latest version

### PR DESCRIPTION
**Pull request by strzh**
@tbordaz  @progier389
Please check and review

### CODE REVIEW

**Comment by strzh** [comment]
related PR https://github.com/389ds/389-ds-base/pull/5930

**Review by progier389 — COMMENTED** [review]
Looks Good !

**Comment by progier389** [comment]
Except that the PR should not have been closed ! IMHO you should reopen it !

**Comment by progier389** [comment]
I understand now why you closed it, it is a duplicate of [PR #5930](https://github.com/389ds/389-ds-base/pull/5930)

**Pull request closed without merging**
