### PR TITLE
Issue 6397 - Remove deprecated setting for HR time stamps in logs

### PR DESCRIPTION
**Pull request by mreynolds389**
Remove the code for checking is CLOCK exists and the logging_hr_timestamps config settings

Also fixed some compiler warnings

relates: https://github.com/389ds/389-ds-base/issues/6397

### CODE REVIEW

**Comment by progier389** [comment]
Looks like all #if(n)def HAVE_CLOCK_GETTIME have been removed except the back-ldbm/vlv.c one. Was it forgotten ?

**Review by droideck — CHANGES_REQUESTED** [review]
Couple of related lines in healthcheck_test were missed:

https://github.com/389ds/389-ds-base/blob/2995fe729b571fdd189fc496fe256778f00ced02/dirsrvtests/tests/suites/healthcheck/healthcheck_test.py#L149

https://github.com/389ds/389-ds-base/blob/2995fe729b571fdd189fc496fe256778f00ced02/dirsrvtests/tests/suites/healthcheck/healthcheck_test.py#L243

The rest looks good!

**Comment by mreynolds389** [comment]
> Looks like all #if(n)def HAVE_CLOCK_GETTIME have been removed except the back-ldbm/vlv.c one. Was it forgotten ?

I don't see HAVE_CLOCK_GETTIME anywhere in the code anymore.  I did add some last minute commits  - maybe you need to refresh the PR?

**Comment by mreynolds389** [comment]
> Couple of related lines in healthcheck_test were missed:
> 

Fixed

**Comment by mreynolds389** [comment]
> > Couple of related lines in healthcheck_test were missed:
> 
> Fixed

All the tests as passing now, can you review this @droideck ?

**Review by droideck — APPROVED** [review]
Looks good!

**Pull request merged**
