### PR TITLE
Issue 5521 - UI - Update plugins for new split PAM and LDAP pass thru auth

### PR DESCRIPTION
**Pull request by mreynolds389**
Description:  Previously PAM and LDAP pass thru auth were merged.  This changes separates them.

relates: https://github.com/389ds/389-ds-base/issues/5521

### CODE REVIEW

**Review by droideck — CHANGES_REQUESTED** [review]
Hmm, something is missing...
I get an error on the build time:

```
ERROR in ./src/plugins.jsx 37:0-73
Module not found: Error: Can't resolve './lib/plugins/pamPassThru.jsx' in '/__w/389-ds-base/389-ds-base/src/cockpit/389-console/src'

webpack compiled with 1 error
make[1]: Leaving directory '/__w/389-ds-base/389-ds-base/src/cockpit/389-console'
make[1]: *** [node_modules.mk:8: build-cockpit-plugin] Error 1
touch: cannot touch 'cockpit_dist/*': No such file or directory
make: *** [rpm.mk:62: dist-bz2] Error 1
```

**Comment by mreynolds389** [comment]
> Hmm, something is missing... I get an error on the build time:
> 
> ```
> ERROR in ./src/plugins.jsx 37:0-73
> Module not found: Error: Can't resolve './lib/plugins/pamPassThru.jsx' in '/__w/389-ds-base/389-ds-base/src/cockpit/389-console/src'
> 
> webpack compiled with 1 error
> make[1]: Leaving directory '/__w/389-ds-base/389-ds-base/src/cockpit/389-console'
> make[1]: *** [node_modules.mk:8: build-cockpit-plugin] Error 1
> touch: cannot touch 'cockpit_dist/*': No such file or directory
> make: *** [rpm.mk:62: dist-bz2] Error 1
> ```

Forget to commit the file, fixed now.

**Comment by droideck** [comment]
Looks good!
One minor issue:
PAM pass-through is not greyed out on loading:

[Screencast from 01-04-2023 10:59:29 AM.webm](https://user-images.githubusercontent.com/5634892/210629567-8d30a1bd-7f9c-4194-b5d5-edc9ac7e85d4.webm)

**Comment by mreynolds389** [comment]
> Looks good! One minor issue: PAM pass-through is not greyed out on loading:

Fixed

**Review by droideck — APPROVED** [review]
LGTM!

**Pull request merged**
