### PR TITLE
Issue 6241 - Add support for CRYPT-YESCRYPT

### LINKED ISSUE #6241: Add support for CRYPT-YESCRYPT
**Is your feature request related to a problem? Please describe.**
Yescrypt has supplanted CRYPT-SHA512 as the default hashing algorithm in many distros including Arch, Debian, and Fedora. It would be nice to also have support for generating passwords using this hashing algorithm in 389-ds-base

**Describe the solution you'd like**
Implement CRYPT-YESCRYPT as a password storage scheme.

### PR DESCRIPTION
**Pull request by jasonborden**
Description:
Implements CRYPT-YESCRYPT as a password storage scheme

Issue: #6241 

Reviewed by: @progier389

### CODE REVIEW

**Comment by jasonborden** [comment]
This PR uses the same defaults parameters as the distros that use yescrypt: 24 b64 salt chars and j9T params. To use yescrypt the system will need libxcrypt 4.2 or higher.

**Review by progier389 — COMMENTED** [review]
Looks good, 
but  I would prefer that we use #define for the standard crypt algorithm id rather than embedding directly the string in the code. 

Maybe a bit picky but this code is sensitive in term of security, 
and it is better make it as easily readable as possible ...

/* Standard Crypt Algorithms identifiers (with usual options when needed) */
#define CRYPT_ALGO_ID_SHA512  "$6$"
#define CRYPT_ALGO_ID_YESCRYPT "$y$j9T$"

**Comment by jasonborden** [comment]
Updated with suggested #defined algorithm IDs and comment.

**Review by progier389 — APPROVED** [review]
Looks good.

**Pull request merged**
