### PR TITLE
Issue 4877 - RFE - EntryUUID to validate UUIDs on fixup

### LINKED ISSUE #4877: EntryUUID fixup to correct invalid entryuuids
Relates #4872 - after the change of this to str syntax, we need a way to fix invalid entryuuids if they are imported.

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: Due to changing the syntax of EntryUUID's
to string, we may have invalid EntryUUID's imported into
the database.

Fix Description: To resolve this during a fixup we validate
that Uuid's have a valid syntax. If they do not, we regenerate
them.

fixes: https://github.com/389ds/389-ds-base/issues/4877

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

**Comment by mreynolds389** [comment]
ack

**Comment by Firstyear** [comment]
@mreynolds389 Do you want me to apply to 1.4.4 and 1.4.3 as well? I think that's what you did for the previous entryuuid change.

**Comment by mreynolds389** [comment]
> @mreynolds389 Do you want me to apply to 1.4.4 and 1.4.3 as well? I think that's what you did for the previous entryuuid change.

Yes please

**Comment by Firstyear** [comment]
I'm about to knock off for the day as I'm super tired - can this wait for next week?

**Comment by Firstyear** [comment]
```
   bce941ec3..193ae2f79  389-ds-base-2.0 -> 389-ds-base-2.0
   66f745864..16124665c  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   0e8d78c17..354e06167  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
```

**Pull request merged**
