### PR TITLE
Localizing Cockpit's 389ds Plugin using CockpitPoPlugin

### PR DESCRIPTION
**Pull request by designet-inc-oss**
Hello,

A while ago, I consulted about this on Issues, and we have now started localizing the 389ds plugin in Cockpit using the CockpitPoPlugin.

Relates: [https://github.com/389ds/389-ds-base/issues/5732](url)

To enable localization for 389ds, we obtained CockpitPoPlugin from pkg/lib/cockpit-po-plugin.js in the old Cockpit, called it in webpack.config.js, and modified the files so that 389ds can handle language files (po files).

Since there are many files to be translated, we only changed src/server.jsx for now. 
To align with the localization of other Cockpit plugins, we define localized strings using an underscore (_).
If there are no issues with this direction of localization, we would like to proceed with making changes to the other files as well.

### CODE REVIEW

**Comment by designet-inc-oss** [comment]
Continuing from yesterday, I made some modifications to several files to make them multilingual.

**Comment by mreynolds389** [comment]
Quick question, is this PR currently only adding support for Japanese?   We would need additional PO files for other languages?  Or this PO file just needed for the unique character set?  Sorry not very familiar with this all of this, so please excuse my ignorance on the topic.

Anyway, this is a lot of work, great job so far!!

**Comment by designet-inc-oss** [comment]
Thank you for your question.

Currently, PO files have been added for Japanese only.
But this is not a complete PO file. This is the content added for confirmation on the screen.

As you are aware, you will need additional PO files to translate into other languages.
This is the same approach to multilingualization of other Cockpit plugins.

For example, to translate to French, you need to create fr.po.

By the way, in other Cockpit plugins PO file generation is done through Makefiles.
So, like other plugins, we would like to be able to programmatically automate the PO file generation.

**Comment by designet-inc-oss** [comment]
Hello,

The multilingualization mechanism has been completed for all files. The parts marked as _("text") are the translation points. Even if there are no po files, the "text" within _("text") will be displayed, so it will still function without po files. We are using gettext for translation, so gettext-parser will be added to the package.json. We have also implemented a helper for converting po files into the format used by Cockpit.

We are planning to create Japanese po files afterward.

**Comment by mreynolds389** [comment]
You might want to rebase with main branch, as I just made some changes to global/local password policy pages.

**Comment by designet-inc-oss** [comment]
Thanks for your advice.

I did a rebase on the main branch.

**Comment by designet-inc-oss** [comment]
Hello.

The Japanese translation has been completed.
We also fixed some localization mistakes found during Japanese translation.
This completes multilingualization and Japaneseization.

To perform localization in other languages, you will need to create a po file for that language and proceed with the translation. I have also added a script to create po files called "mk_po.sh."

When you execute mk_po.sh, it will export the parts marked as _("text") in the program to the po file.

Here's how to use mk_po.sh, using French as an example:

1. Change LANG_CODE to the language code you want to translate and save the file.
```
$ vi mk_po.sh
LANG_CODE="fr"
```

2. Execute it in the "389-ds-base/src/cockpit/389-console" directory.
```
$ sh mk_po.sh
```

3. Move the generated po file to the po directory.
```
$ mv fr.po po/
```

4. Set the **Language** field in the po file and fill the **msgstr** line with the translated string.
```
$ vi po/fr.po
:
"Language: fr\n"
:
#: src/lib/replication/replSuffix.jsx:186
msgid "The Bind DN is not a valid DN (Distinguished Name) $0"
msgstr ""
```

5. Afterward, simply execute buildAndRun.sh.

If the po file is not present, the "text" inside _("text") will be displayed as it is. Hence, the functionality will still work even without the po file.

**Comment by mreynolds389** [comment]
Thanks for the all work on this one!!  I will review/test this later this week and we will get merged soon!

**Comment by mreynolds389** [comment]
This patch does not apply on main branch, maybe you need to rebase it?

**Comment by mreynolds389** [comment]
> This patch does not apply on main branch, maybe you need to rebase it?

@designet-inc Sorry to pester you but this PR needs to be rebased and conflicts resolved so we can get it merged.  The longer the rebase takes the more this PR is going to fall out of sync.

**Comment by designet-inc-oss** [comment]
@mreynolds389 
I apologize for the delay.
I have resolved the conflicts and performed a rebase.
Please review it.

**Review by mreynolds389 — APPROVED** [review]
I found no regressions, ACK

**Comment by mreynolds389** [comment]
Before we can merge, can you please "squash" all 38 commits into a single one?  And at the same time set the commit message following our guidelines:

https://www.port389.org/docs/389ds/contributing.html#getting-the-patch-ready

Thanks!

**Comment by designet-inc-oss** [comment]
@mreynolds389 

Thank you for your continuous support.

Based on the URL you provided, I have compressed the commit I made into a single one. 
Please review it.
Best regards.

**Comment by mreynolds389** [comment]
> @mreynolds389
> 
> Thank you for your continuous support.
> 
> Based on the URL you provided, I have compressed the commit I made into a single one. Please review it. Best regards.

Sorry, but it's still two commits, and this can not be merged due to conflicts with "main" branch.  So it needs to be rebased again, and the conflicts fixed, then it needs to be squashed into a single commit.

**Comment by designet-inc-oss** [comment]
@mreynolds389 

I made several mistakes again... I think this should make one commit and not conflict with "main," but could you please confirm for me? I apologize for the inconvenience and appreciate your assistance in checking.

**Comment by mreynolds389** [comment]
Sorry I didn't get around to testing this and now the patch does not apply again.  But it is a single patch/commit, nice!  However you need to rebase and fix some conflicts :-(

FYI, there are no UI updates planned on our side, so this should be the last time you need to do anything.

**Comment by designet-inc-oss** [comment]
@mreynolds389 

Thank you for your response.
I have rebased again and resolved the conflicts.
Since all the commits are now merged into one, I believe everything should be fine. What do you think?
Please review and confirm.

**Comment by droideck** [comment]
@designet-inc-oss hi!
Sorry to block the merge a bit more.

I've just tried to switch the language with the PR, and it gives me the next set of errors when I switch to Japanese:

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
updates.js:155 Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"不允许执行该操作。"}", data: "undefined"
(anonymous) @ updates.js:155
2index.js:16 One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
render @ index.js:16
index.js:15 CMD: loadInstanceList: Load the instance list select ==> dsctl -l -j
overview.js:134 can't get NTPSynchronized property be
shell.js:8 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at E5 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:25573)
    at sa (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:30799)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27834)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27826)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27629)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27629)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
B5 @ shell.js:8
shell.js:6 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at E5 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:25573)
    at sa (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:30799)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27834)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27826)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27629)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
    at s1 (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27629)
    at Nr (https://10.0.185.79:9090/cockpit/@localhost/shell/shell.js:8:27516)
translate.googleapis.com/element/log?format=json&hasfast=true&authuser=0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
389-console:1 Refused to load the stylesheet 'https://www.gstatic.com/_/translate_http/_/ss/k=translate_http.tr.qhDXWpKopYk.L.W.O/d=0/rs=AN8SPfp0QXhhaDDdjg_LgcSqoZiPEzC1tw/m=el_main_css' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

VM60:26     POST https://translate.googleapis.com/element/log?format=json&hasfast=true&authuser=0 net::ERR_BLOCKED_BY_CLIENT
_.Zg.send @ m=el_conf:586
_.Pi @ VM60:26
tr.send @ VM60:222
r @ VM60:217
eval @ VM60:218
Promise.then (async)
hr.flush @ VM60:217
eval @ VM60:212
Zd @ m=el_conf:521
_.k.dispatchEvent @ m=el_conf:520
Mo.A @ VM60:174
Show 3 more frames
Show less
8updates.js:12 Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
(anonymous) @ updates.js:12
QY @ updates.js:8
UY @ updates.js:8
ALe @ updates.js:8
$I @ updates.js:8
VY @ updates.js:8
aE @ updates.js:1
J3 @ updates.js:1
VM60:26     POST https://translate.googleapis.com/element/log?format=json&hasfast=true&authuser=0 net::ERR_BLOCKED_BY_CLIENT
```

I've rebased onto the current `main` branch, so it should be up to date...

**Comment by vashirov** [comment]
@droideck, I can't reproduce this error. I can switch to Japanese language without any issues. In the backtrace there are links to Google Translate, perhaps you have an extension installed or your browser tries to translate the text back to English? Can you try without an extension or disable autotranslate feature?

**Comment by droideck** [comment]
> @droideck, I can't reproduce this error. I can switch to Japanese language without any issues. In the backtrace there are links to Google Translate, perhaps you have an extension installed or your browser tries to translate the text back to English? Can you try without an extension or disable autotranslate feature?

Okay, right... It's not related to this PR.

And yep, it's Chrome thingy (google translate)  and it's not related to Japanese. It fails with English too (if I try to translate it to Russian, for example).

I'll open a new issue as it's still a bug which I wasn't able to reproduce in other Cockpit parts, it happens only in 389 DS, as far as I can see.

So I'll merge this PR, if you're okay with that. And I'll backport it to other branches up to 1.4.3, I guess?

@designet-inc-oss Sorry for the fuss and thanks once again for the contribution!

**Comment by mreynolds389** [comment]
> So I'll merge this PR, if you're okay with that. And I'll backport it to other branches up to 1.4.3, I guess?

Perhaps this should stay in 2.3/2.4 until it's fully vetted?  Also, I don't think it's going to backport well to older branches that do not have the esbundler changes.

**Comment by droideck** [comment]
> > So I'll merge this PR, if you're okay with that. And I'll backport it to other branches up to 1.4.3, I guess?
> 
> Perhaps this should stay in 2.3/2.4 until it's fully vetted? Also, I don't think it's going to backport well to older branches that do not have the esbundler changes.

Good point.
Yeah, I guess now, some changes are better to stay in 2.3/2.4 when possible, as the https://github.com/389ds/389-ds-base/issues/5793 change was huge...

**Review by vashirov — APPROVED** [review]

**Review by droideck — APPROVED** [review]

**Pull request merged**
