### PR TITLE
Issue 5581 - UI - Support cockpit dark theme

### PR DESCRIPTION
**Pull request by mreynolds389**
Description:  We were previously overriding the background color which caused
              issues with the dark theme.

relates: https://github.com/389ds/389-ds-base/issues/5581

### CODE REVIEW

**Comment by droideck** [comment]
Looks great and clean!
I have one minor concern only - the red text colour (for example, during instance creation)
I think it'll look much cleaner if we use the lighter one (it's already used in other places in Cockpit with Dark mode):

Basically, we use `--pf-global--danger-color--100` - `#fe5142`. And the rest of the cockpit uses `--pf-global--danger-color--200` - `#ff7468`
image

Ideally, we need to change the colour of the `(!)` icon too (it's also `#ff7468` color in the rest of the cockpit)

Current colour:
image

Suggested colour:
image

**Comment by mreynolds389** [comment]
@droideck - oh ok you want to override PF classes.  I tried inspecting that element and I couldn't find what sets the color.  How are you overriding it?

**Comment by mreynolds389** [comment]
> @droideck - oh ok you want to override PF classes. I tried inspecting that element and I couldn't find what sets the color. How are you overriding it?

Nevermind I found it

**Comment by mreynolds389** [comment]
@droideck - its all fixed.  Also found a bug when editing groups that would crash the browser and also updates Database tree (replaced the "Create Suffix" button with a  tree action item icon).

**Review by droideck — APPROVED** [review]
Looks great! Ack

**Pull request merged**
