### PR TITLE
 Issue 5565 - Add Rust password storage PBKDF2 schemes

### PR DESCRIPTION
**Pull request by droideck**
Description: 389-ds-base-1.3.x does not support the Rust password hashers. If you replicate between 389-ds-1.4.x (or higher) and 1.3.x then all authentication will start failing on 1.3.x.
Backport Rust PBKDF2 implementation to 1.3.10.

Related: https://github.com/389ds/389-ds-base/issues/5565

Reviwed by: ?

### CODE REVIEW

**Comment by droideck** [comment]
@Firstyear check it out. Rust in 1.3.10!

**Comment by Firstyear** [comment]
> @Firstyear check it out. Rust in 1.3.10!

Scary 😳

**Review by Firstyear — APPROVED** [review]
Looks really good :) well done!

**Comment by tbordaz** [comment]
The support of PBKDF2_SHA512 in 1.3.10 is a requirement to enable it by default in 1.4.3 (RHEL8). However is it a requirement to make it the default hash in 1.3.10 ?
I agree that eventually it will be the default hash scheme (in all versions) but from a deployment pov I see no benefit to force a CU to update a full 1.3.10 topology. We can imagine an admin that applies this patch only on a subset of servers.

**Comment by droideck** [comment]
> The support of PBKDF2_SHA512 in 1.3.10 is a requirement to enable it by default in 1.4.3 (RHEL8). However is it a requirement to make it the default hash in 1.3.10 ? I agree that eventually it will be the default hash scheme (in all versions) but from a deployment pov I see no benefit to force a CU to update a full 1.3.10 topology. We can imagine an admin that applies this patch only on a subset of servers.

Couple of things to consider:

- The initial decision to update happened because of security/performance reasons, more covered here: https://github.com/389ds/389-ds-base/issues/5356
- We don't have the "password hash upgrade on bind" feature in 1.3.10, so it won't be a full 1.3.10 topology upgrade, as only the new users' passwords will be hashed with PBKDF2-SHA512. 

So I think it's really more of a management decision of the direction we want it present to our users:

1. Leave SSHA512 in 1.3.10 but switch to PBKDF2-SHA512 in 1.4.3 and 2.x. And recommend they set PBKDF2-SHA512 in their 1.3.10 topologies.
2. Or move every branch to PBKDF2-SHA512 as a default.

@mreynolds389, what do you think?

**Comment by mreynolds389** [comment]
> So I think it's really more of a management decision of the direction we want it present to our users:
> 
>     1. Leave SSHA512 in 1.3.10 but switch to PBKDF2-SHA512 in 1.4.3 and 2.x. And recommend they set PBKDF2-SHA512 in their 1.3.10 topologies.
> 
>     2. Or move every branch to PBKDF2-SHA512 as a default.
> 
> 
> @mreynolds389, what do you think?

Do not make PBDFK2 the default in 1.3.x.  It just needs to be supported.  You should never change default behavior this late into a release (especially PBKDF2 as it significantly slows down a bind and this would catch a lot of customers off guard after just doing an update).

Thanks!

**Comment by droideck** [comment]
Sure thing!
The changes are made. Please, review. (And I'm running tests once again, just in case)

**Review by tbordaz — APPROVED** [review]

**Comment by droideck** [comment]
I accidentally merged the old commit message `Issue 5565 - Change default password storage scheme to PBKDF2-SHA512 (#5616)`. The actual code doesn't change the default storage scheme.
@mreynolds389 if you'll be doing the downstream build, please, be aware of that... Sorry for the inconvenience. :(

**Pull request merged**
