### PR TITLE
Issue 4901 - Add COPR integration

### LINKED ISSUE #4901: Add COPR integration
**Issue Description**
Fedora COPR supports automatic rebuilds from SCM:
https://docs.pagure.org/copr.copr/user_documentation.html#scm
And GitHub webhooks to automatically trigger builds:
https://docs.pagure.org/copr.copr/user_documentation.html#github-webhooks

### PR DESCRIPTION
**Pull request by vashirov**
Description:
Fedora COPR supports automatic rebuilds from SCM:
https://docs.pagure.org/copr.copr/user_documentation.html#scm
And GitHub webhooks to automatically trigger builds:
https://docs.pagure.org/copr.copr/user_documentation.html#github-webhooks

Fixes: https://github.com/389ds/389-ds-base/issues/4901

Reviewed by: ???

### CODE REVIEW

**Comment by mreynolds389** [comment]
Took a quick look at this, but how does this trigger copr builds exactly?  

I see nothing mentioning COPR or https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/

**Comment by vashirov** [comment]
It uses a webhook configured for our GitHub project. See https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/integrations/
I've already added [one](https://github.com/389ds/389-ds-base/settings/hooks/316794007), but kept it inactive. On every push GitHub will POST json payload to COPR, and it will trigger a build. It also needs to be configured to use `make srpm` method, see [here](https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/package/389-ds-base/edit).

**Comment by mreynolds389** [comment]
Ack!

**Comment by vashirov** [comment]
I've updated the webhook and SCM build method. COPR build was triggered: https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/build/2683168/

**Review by mreynolds389 — COMMENTED** [review]
I know this was merged, but I wonder if the we need the "SKIP_AUDIT_CI=1" env var set?  

When I run it, it fails for me:
```
# make -f rpm.mk srpms
...
...
found 0 vulnerabilities
make[1]: Leaving directory '/home/mareynol/source/ds389/389-ds-base/src/cockpit/389-console'
cd src/cockpit/389-console; \
rm -rf cockpit_dist; \
NODE_ENV=production make -f node_modules.mk build-cockpit-plugin
make[1]: Entering directory '/home/mareynol/source/ds389/389-ds-base/src/cockpit/389-console'
npm run audit-ci

> 389-console@1.0.0 audit-ci
> audit-ci --config audit-ci.json

audit-ci version: 3.2.0
Cannot convert undefined or null to object
Exiting...
```

**Comment by vashirov** [comment]
I forgot about it because `npm audit-ci` passed in COPR and didn't fail the build for the first time in ages :) 
It also passes for me:
```
> 389-console@1.0.0 audit-ci /home/vashirov/src/ds/src/cockpit/389-console
> audit-ci --config audit-ci.json

audit-ci version: 3.2.0
NPM audit report results:
{
  "advisories": {},
  "metadata": {
    "vulnerabilities": {
      "info": 0,
      "low": 0,
      "moderate": 0,
      "high": 0,
      "critical": 0
    },
    "dependencies": 92,
    "devDependencies": 1,
    "optionalDependencies": 0,
    "totalDependencies": 93
  }
}
Passed npm security audit.

```
Could you please try on a clean git tree? Maybe something in `node_modules` causes `npm auidit-ci` to fail.

We need to add the env var though, since the builds are used for FreeIPA testing. 
But I'd like to add a separate GH action to monitor the status of `npm auidit-ci` too.
I'll open a new PR today.

**Comment by mreynolds389** [comment]
I tried fresh checkout, same issue on Fedora 34:

audit-ci version: 3.2.0
Cannot convert undefined or null to object
Exiting...

[mareynol@fedora 389-console]$ npm -v run audit-ci -d
npm info using npm@7.17.0
npm info using node@v14.17.0

**Comment by vashirov** [comment]
What npm registries do you have configured? 
Does it work if you specify it explicitly like so:
```
cd src/cockpit/389-console
npx audit-ci --registry=https://registry.npmjs.org/ --config audit-ci.json
```

**Comment by mreynolds389** [comment]
> What npm registries do you have configured?
> Does it work if you specify it explicitly like so:
> 
> ```
> cd src/cockpit/389-console
> npx audit-ci --registry=https://registry.npmjs.org/ --config audit-ci.json
> ```

Nope still fails :-(

**Comment by mreynolds389** [comment]
> Does it work for you on any other machine?
> Can you access the default registry at all?
> 
> ```
> curl https://registry.npmjs.org/
> ```

I can access it from my laptop.  

But yeah it probably is something with my system, but what the issue is I don't know.  However, it could happen on other systems too.  So while I don't want to skip the audit check, I also don't want nightly builds to incorrectly fail because of it (this is now addressed, but it would be nice to eventually find out what is wrong with my system).

**Pull request merged**
