### PR TITLE
Cleanup github compiler & clang warnings

### PR DESCRIPTION
**Pull request by mreynolds389**
Cleanup github compiler & clang warnings.

### CODE REVIEW

**Review by Firstyear — APPROVED** [review]
Great stuff 🎉

**Review by Firstyear — APPROVED** [review]
Ack from me

**Comment by mreynolds389** [comment]
This is a can of worms.  Now matter how many I fix it still reports more.  The results must be truncated.  There are some good changes here, but it's not going to clean up what github reports in PR's :-(

**Comment by Firstyear** [comment]
Doesn't have to be perfect man, just incremental improvement :)

**Pull request merged**
