### PR TITLE
Issue 5356 - Make Rust non-optional and update default password storage

### PR DESCRIPTION
**Pull request by mreynolds389**
Make Rust non-optional and update default password storage scheme

Description:

We need a stronger default storage scheme which comes from our Rust
plugins, but to do this  Rust needs to be non-optional.  It will be
a requirement moving forward.

relates: https://github.com/389ds/389-ds-base/issues/5356

Reviewed by: ?

### CODE REVIEW

**Review by Firstyear — APPROVED** [review]
Huge and enthusiastic yes from me!

**Comment by droideck** [comment]
I see a few new failures. I wonder if our CI went crazy or if something is up with the PR...
Rerunning.

**Comment by vashirov** [comment]
healthcheck and [tests](https://github.com/389ds/389-ds-base/blob/main/dirsrvtests/tests/suites/healthcheck/health_security_test.py#L71
) for it complain that our new default storage scheme is weak. I think lint.py should be updated too:
https://github.com/389ds/389-ds-base/blob/dea9f6a7cd6d1c4029705559c69c273584a53561/src/lib389/lib389/lint.py#L97-L98



`pwp_test.py` expects a different default password storage scheme:
https://github.com/389ds/389-ds-base/blob/dea9f6a7cd6d1c4029705559c69c273584a53561/dirsrvtests/tests/suites/password/pwp_test.py#L30

and [`dscreate_test.py::test_setup_ds_as_non_root`](https://github.com/389ds/389-ds-base/blob/main/dirsrvtests/tests/suites/setup_ds/dscreate_test.py#L182) fails with
```
[24/Aug/2022:04:20:50.731427271 +0000] - ERR - slapd_bootstrap_config - The default password storage scheme could not be read or was not found in the file /tmp/tmphu0fk5_5/root/etc/dirsrv/slapd-standalone/dse.ldif. It is mandatory.

```

**Comment by mreynolds389** [comment]
I don't see any regressions in CI tests with my last commit.  Merging...

**Pull request merged**
